/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: forwardbutton_S                                       *
* Dimensions:  43 * 43                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsforwardbutton_S[] = {
     0xFFFFFF,0xFF0000,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palforwardbutton_S = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsforwardbutton_S[0]
};

static GUI_CONST_STORAGE unsigned char acforwardbutton_S[] = {
  /* RLE: 220 Pixels @ 000,000*/ 220, 0x00, 
  /* RLE: 008 Pixels @ 005,005*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,005*/ 6, 0x00, 
  /* RLE: 004 Pixels @ 019,005*/ 4, 0x01, 
  /* RLE: 025 Pixels @ 023,005*/ 25, 0x00, 
  /* RLE: 008 Pixels @ 005,006*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,006*/ 6, 0x00, 
  /* RLE: 004 Pixels @ 019,006*/ 4, 0x01, 
  /* RLE: 025 Pixels @ 023,006*/ 25, 0x00, 
  /* RLE: 008 Pixels @ 005,007*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,007*/ 6, 0x00, 
  /* RLE: 005 Pixels @ 019,007*/ 5, 0x01, 
  /* RLE: 024 Pixels @ 024,007*/ 24, 0x00, 
  /* RLE: 008 Pixels @ 005,008*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,008*/ 6, 0x00, 
  /* RLE: 007 Pixels @ 019,008*/ 7, 0x01, 
  /* RLE: 022 Pixels @ 026,008*/ 22, 0x00, 
  /* RLE: 008 Pixels @ 005,009*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,009*/ 6, 0x00, 
  /* RLE: 007 Pixels @ 019,009*/ 7, 0x01, 
  /* RLE: 022 Pixels @ 026,009*/ 22, 0x00, 
  /* RLE: 008 Pixels @ 005,010*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,010*/ 6, 0x00, 
  /* RLE: 008 Pixels @ 019,010*/ 8, 0x01, 
  /* RLE: 021 Pixels @ 027,010*/ 21, 0x00, 
  /* RLE: 008 Pixels @ 005,011*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,011*/ 6, 0x00, 
  /* RLE: 010 Pixels @ 019,011*/ 10, 0x01, 
  /* RLE: 019 Pixels @ 029,011*/ 19, 0x00, 
  /* RLE: 008 Pixels @ 005,012*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,012*/ 6, 0x00, 
  /* RLE: 010 Pixels @ 019,012*/ 10, 0x01, 
  /* RLE: 019 Pixels @ 029,012*/ 19, 0x00, 
  /* RLE: 008 Pixels @ 005,013*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,013*/ 6, 0x00, 
  /* RLE: 012 Pixels @ 019,013*/ 12, 0x01, 
  /* RLE: 017 Pixels @ 031,013*/ 17, 0x00, 
  /* RLE: 008 Pixels @ 005,014*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,014*/ 6, 0x00, 
  /* RLE: 012 Pixels @ 019,014*/ 12, 0x01, 
  /* RLE: 017 Pixels @ 031,014*/ 17, 0x00, 
  /* RLE: 008 Pixels @ 005,015*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,015*/ 6, 0x00, 
  /* RLE: 013 Pixels @ 019,015*/ 13, 0x01, 
  /* RLE: 016 Pixels @ 032,015*/ 16, 0x00, 
  /* RLE: 008 Pixels @ 005,016*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,016*/ 6, 0x00, 
  /* RLE: 015 Pixels @ 019,016*/ 15, 0x01, 
  /* RLE: 014 Pixels @ 034,016*/ 14, 0x00, 
  /* RLE: 008 Pixels @ 005,017*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,017*/ 6, 0x00, 
  /* RLE: 015 Pixels @ 019,017*/ 15, 0x01, 
  /* RLE: 014 Pixels @ 034,017*/ 14, 0x00, 
  /* RLE: 008 Pixels @ 005,018*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,018*/ 6, 0x00, 
  /* RLE: 016 Pixels @ 019,018*/ 16, 0x01, 
  /* RLE: 013 Pixels @ 035,018*/ 13, 0x00, 
  /* RLE: 008 Pixels @ 005,019*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,019*/ 6, 0x00, 
  /* RLE: 018 Pixels @ 019,019*/ 18, 0x01, 
  /* RLE: 011 Pixels @ 037,019*/ 11, 0x00, 
  /* RLE: 008 Pixels @ 005,020*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,020*/ 6, 0x00, 
  /* RLE: 018 Pixels @ 019,020*/ 18, 0x01, 
  /* RLE: 011 Pixels @ 037,020*/ 11, 0x00, 
  /* RLE: 008 Pixels @ 005,021*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,021*/ 6, 0x00, 
  /* RLE: 019 Pixels @ 019,021*/ 19, 0x01, 
  /* RLE: 010 Pixels @ 038,021*/ 10, 0x00, 
  /* RLE: 008 Pixels @ 005,022*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,022*/ 6, 0x00, 
  /* RLE: 019 Pixels @ 019,022*/ 19, 0x01, 
  /* RLE: 001 Pixels @ 038,022*/ 1, 0x02, 
  /* RLE: 009 Pixels @ 039,022*/ 9, 0x00, 
  /* RLE: 008 Pixels @ 005,023*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,023*/ 6, 0x00, 
  /* RLE: 018 Pixels @ 019,023*/ 18, 0x01, 
  /* ABS: 002 Pixels @ 037,023*/ 0, 2, 0x02, 0x02, 
  /* RLE: 009 Pixels @ 039,023*/ 9, 0x00, 
  /* RLE: 008 Pixels @ 005,024*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,024*/ 6, 0x00, 
  /* RLE: 016 Pixels @ 019,024*/ 16, 0x01, 
  /* RLE: 003 Pixels @ 035,024*/ 3, 0x02, 
  /* RLE: 010 Pixels @ 038,024*/ 10, 0x00, 
  /* RLE: 008 Pixels @ 005,025*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,025*/ 6, 0x00, 
  /* RLE: 016 Pixels @ 019,025*/ 16, 0x01, 
  /* RLE: 003 Pixels @ 035,025*/ 3, 0x02, 
  /* RLE: 010 Pixels @ 038,025*/ 10, 0x00, 
  /* RLE: 008 Pixels @ 005,026*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,026*/ 6, 0x00, 
  /* RLE: 015 Pixels @ 019,026*/ 15, 0x01, 
  /* RLE: 003 Pixels @ 034,026*/ 3, 0x02, 
  /* RLE: 011 Pixels @ 037,026*/ 11, 0x00, 
  /* RLE: 008 Pixels @ 005,027*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,027*/ 6, 0x00, 
  /* RLE: 013 Pixels @ 019,027*/ 13, 0x01, 
  /* RLE: 003 Pixels @ 032,027*/ 3, 0x02, 
  /* RLE: 013 Pixels @ 035,027*/ 13, 0x00, 
  /* RLE: 008 Pixels @ 005,028*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,028*/ 6, 0x00, 
  /* RLE: 013 Pixels @ 019,028*/ 13, 0x01, 
  /* RLE: 003 Pixels @ 032,028*/ 3, 0x02, 
  /* RLE: 013 Pixels @ 035,028*/ 13, 0x00, 
  /* RLE: 008 Pixels @ 005,029*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,029*/ 6, 0x00, 
  /* RLE: 012 Pixels @ 019,029*/ 12, 0x01, 
  /* RLE: 003 Pixels @ 031,029*/ 3, 0x02, 
  /* RLE: 014 Pixels @ 034,029*/ 14, 0x00, 
  /* RLE: 008 Pixels @ 005,030*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,030*/ 6, 0x00, 
  /* RLE: 011 Pixels @ 019,030*/ 11, 0x01, 
  /* ABS: 002 Pixels @ 030,030*/ 0, 2, 0x02, 0x02, 
  /* RLE: 016 Pixels @ 032,030*/ 16, 0x00, 
  /* RLE: 008 Pixels @ 005,031*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,031*/ 6, 0x00, 
  /* RLE: 010 Pixels @ 019,031*/ 10, 0x01, 
  /* ABS: 002 Pixels @ 029,031*/ 0, 2, 0x02, 0x02, 
  /* RLE: 017 Pixels @ 031,031*/ 17, 0x00, 
  /* RLE: 008 Pixels @ 005,032*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,032*/ 6, 0x00, 
  /* RLE: 008 Pixels @ 019,032*/ 8, 0x01, 
  /* RLE: 003 Pixels @ 027,032*/ 3, 0x02, 
  /* RLE: 018 Pixels @ 030,032*/ 18, 0x00, 
  /* RLE: 008 Pixels @ 005,033*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,033*/ 6, 0x00, 
  /* RLE: 008 Pixels @ 019,033*/ 8, 0x01, 
  /* RLE: 003 Pixels @ 027,033*/ 3, 0x02, 
  /* RLE: 018 Pixels @ 030,033*/ 18, 0x00, 
  /* RLE: 008 Pixels @ 005,034*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,034*/ 6, 0x00, 
  /* RLE: 007 Pixels @ 019,034*/ 7, 0x01, 
  /* RLE: 003 Pixels @ 026,034*/ 3, 0x02, 
  /* RLE: 019 Pixels @ 029,034*/ 19, 0x00, 
  /* RLE: 008 Pixels @ 005,035*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,035*/ 6, 0x00, 
  /* RLE: 005 Pixels @ 019,035*/ 5, 0x01, 
  /* RLE: 003 Pixels @ 024,035*/ 3, 0x02, 
  /* RLE: 021 Pixels @ 027,035*/ 21, 0x00, 
  /* RLE: 008 Pixels @ 005,036*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,036*/ 6, 0x00, 
  /* RLE: 005 Pixels @ 019,036*/ 5, 0x01, 
  /* RLE: 003 Pixels @ 024,036*/ 3, 0x02, 
  /* RLE: 021 Pixels @ 027,036*/ 21, 0x00, 
  /* RLE: 008 Pixels @ 005,037*/ 8, 0x01, 
  /* RLE: 006 Pixels @ 013,037*/ 6, 0x00, 
  /* RLE: 004 Pixels @ 019,037*/ 4, 0x01, 
  /* RLE: 003 Pixels @ 023,037*/ 3, 0x02, 
  /* RLE: 024 Pixels @ 026,037*/ 24, 0x00, 
  /* RLE: 006 Pixels @ 007,038*/ 6, 0x02, 
  /* RLE: 008 Pixels @ 013,038*/ 8, 0x00, 
  /* RLE: 003 Pixels @ 021,038*/ 3, 0x02, 
  /* RLE: 191 Pixels @ 024,038*/ 191, 0x00, 


  0};  /* 312 bytes for 1849 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmforwardbutton_S = {
  43, /* XSize */
  43, /* YSize */
  43, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acforwardbutton_S,  /* Pointer to picture data (indices) */
  &Palforwardbutton_S,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
