/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: pausebutton_S                                         *
* Dimensions:  43 * 43                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorspausebutton_S[] = {
     0xFFFFFF,0x00F6FF,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palpausebutton_S = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorspausebutton_S[0]
};

static GUI_CONST_STORAGE unsigned char acpausebutton_S[] = {
  /* RLE: 226 Pixels @ 000,000*/ 226, 0x00, 
  /* RLE: 007 Pixels @ 011,005*/ 7, 0x01, 
  /* RLE: 008 Pixels @ 018,005*/ 8, 0x00, 
  /* RLE: 006 Pixels @ 026,005*/ 6, 0x01, 
  /* RLE: 022 Pixels @ 032,005*/ 22, 0x00, 
  /* RLE: 007 Pixels @ 011,006*/ 7, 0x01, 
  /* RLE: 008 Pixels @ 018,006*/ 8, 0x00, 
  /* RLE: 006 Pixels @ 026,006*/ 6, 0x01, 
  /* RLE: 022 Pixels @ 032,006*/ 22, 0x00, 
  /* RLE: 007 Pixels @ 011,007*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,007*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,007*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,007*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,007*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,007*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,008*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,008*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,008*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,008*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,008*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,008*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,009*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,009*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,009*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,009*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,009*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,009*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,010*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,010*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,010*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,010*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,010*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,010*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,011*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,011*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,011*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,011*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,011*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,011*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,012*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,012*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,012*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,012*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,012*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,012*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,013*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,013*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,013*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,013*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,013*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,013*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,014*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,014*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,014*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,014*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,014*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,014*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,015*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,015*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,015*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,015*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,015*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,015*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,016*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,016*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,016*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,016*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,016*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,016*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,017*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,017*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,017*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,017*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,017*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,017*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,018*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,018*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,018*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,018*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,018*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,018*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,019*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,019*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,019*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,019*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,019*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,019*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,020*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,020*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,020*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,020*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,020*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,020*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,021*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,021*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,021*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,021*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,021*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,021*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,022*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,022*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,022*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,022*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,022*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,022*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,023*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,023*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,023*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,023*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,023*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,023*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,024*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,024*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,024*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,024*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,024*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,024*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,025*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,025*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,025*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,025*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,025*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,025*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,026*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,026*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,026*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,026*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,026*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,026*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,027*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,027*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,027*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,027*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,027*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,027*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,028*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,028*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,028*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,028*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,028*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,028*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,029*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,029*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,029*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,029*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,029*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,029*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,030*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,030*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,030*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,030*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,030*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,030*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,031*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,031*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,031*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,031*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,031*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,031*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,032*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,032*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,032*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,032*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,032*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,032*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,033*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,033*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,033*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,033*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,033*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,033*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,034*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,034*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,034*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,034*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,034*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,034*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,035*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,035*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,035*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,035*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,035*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,035*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,036*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,036*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,036*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,036*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,036*/ 0, 2, 0x02, 0x02, 
  /* RLE: 020 Pixels @ 034,036*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 011,037*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 018,037*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 019,037*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 026,037*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 032,037*/ 0, 2, 0x02, 0x02, 
  /* RLE: 022 Pixels @ 034,037*/ 22, 0x00, 
  /* RLE: 006 Pixels @ 013,038*/ 6, 0x02, 
  /* RLE: 008 Pixels @ 019,038*/ 8, 0x00, 
  /* RLE: 007 Pixels @ 027,038*/ 7, 0x02, 
  /* RLE: 181 Pixels @ 034,038*/ 181, 0x00, 


  0};  /* 460 bytes for 1849 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmpausebutton_S = {
  43, /* XSize */
  43, /* YSize */
  43, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acpausebutton_S,  /* Pointer to picture data (indices) */
  &Palpausebutton_S,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
