/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: rewindbutton_S                                        *
* Dimensions:  43 * 43                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsrewindbutton_S[] = {
     0xFFFFFF,0xFF0000,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palrewindbutton_S = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsrewindbutton_S[0]
};

static GUI_CONST_STORAGE unsigned char acrewindbutton_S[] = {
  /* RLE: 236 Pixels @ 000,000*/ 236, 0x00, 
  /* RLE: 003 Pixels @ 021,005*/ 3, 0x01, 
  /* RLE: 007 Pixels @ 024,005*/ 7, 0x00, 
  /* RLE: 007 Pixels @ 031,005*/ 7, 0x01, 
  /* RLE: 026 Pixels @ 038,005*/ 26, 0x00, 
  /* RLE: 003 Pixels @ 021,006*/ 3, 0x01, 
  /* RLE: 007 Pixels @ 024,006*/ 7, 0x00, 
  /* RLE: 007 Pixels @ 031,006*/ 7, 0x01, 
  /* RLE: 024 Pixels @ 038,006*/ 24, 0x00, 
  /* RLE: 005 Pixels @ 019,007*/ 5, 0x01, 
  /* ABS: 002 Pixels @ 024,007*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,007*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,007*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,007*/ 1, 0x02, 
  /* RLE: 022 Pixels @ 039,007*/ 22, 0x00, 
  /* RLE: 006 Pixels @ 018,008*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 024,008*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,008*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,008*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,008*/ 1, 0x02, 
  /* RLE: 022 Pixels @ 039,008*/ 22, 0x00, 
  /* RLE: 006 Pixels @ 018,009*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 024,009*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,009*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,009*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,009*/ 1, 0x02, 
  /* RLE: 020 Pixels @ 039,009*/ 20, 0x00, 
  /* RLE: 008 Pixels @ 016,010*/ 8, 0x01, 
  /* ABS: 002 Pixels @ 024,010*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,010*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,010*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,010*/ 1, 0x02, 
  /* RLE: 019 Pixels @ 039,010*/ 19, 0x00, 
  /* RLE: 009 Pixels @ 015,011*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 024,011*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,011*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,011*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,011*/ 1, 0x02, 
  /* RLE: 019 Pixels @ 039,011*/ 19, 0x00, 
  /* RLE: 009 Pixels @ 015,012*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 024,012*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,012*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,012*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,012*/ 1, 0x02, 
  /* RLE: 017 Pixels @ 039,012*/ 17, 0x00, 
  /* RLE: 011 Pixels @ 013,013*/ 11, 0x01, 
  /* ABS: 002 Pixels @ 024,013*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,013*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,013*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,013*/ 1, 0x02, 
  /* RLE: 017 Pixels @ 039,013*/ 17, 0x00, 
  /* RLE: 011 Pixels @ 013,014*/ 11, 0x01, 
  /* ABS: 002 Pixels @ 024,014*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,014*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,014*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,014*/ 1, 0x02, 
  /* RLE: 015 Pixels @ 039,014*/ 15, 0x00, 
  /* RLE: 013 Pixels @ 011,015*/ 13, 0x01, 
  /* ABS: 002 Pixels @ 024,015*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,015*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,015*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,015*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 039,015*/ 14, 0x00, 
  /* RLE: 014 Pixels @ 010,016*/ 14, 0x01, 
  /* ABS: 002 Pixels @ 024,016*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,016*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,016*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,016*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 039,016*/ 14, 0x00, 
  /* RLE: 014 Pixels @ 010,017*/ 14, 0x01, 
  /* ABS: 002 Pixels @ 024,017*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,017*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,017*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,017*/ 1, 0x02, 
  /* RLE: 012 Pixels @ 039,017*/ 12, 0x00, 
  /* RLE: 016 Pixels @ 008,018*/ 16, 0x01, 
  /* ABS: 002 Pixels @ 024,018*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,018*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,018*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,018*/ 1, 0x02, 
  /* RLE: 011 Pixels @ 039,018*/ 11, 0x00, 
  /* RLE: 017 Pixels @ 007,019*/ 17, 0x01, 
  /* ABS: 002 Pixels @ 024,019*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,019*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,019*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,019*/ 1, 0x02, 
  /* RLE: 011 Pixels @ 039,019*/ 11, 0x00, 
  /* RLE: 017 Pixels @ 007,020*/ 17, 0x01, 
  /* ABS: 002 Pixels @ 024,020*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,020*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,020*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,020*/ 1, 0x02, 
  /* RLE: 009 Pixels @ 039,020*/ 9, 0x00, 
  /* RLE: 019 Pixels @ 005,021*/ 19, 0x01, 
  /* ABS: 002 Pixels @ 024,021*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,021*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,021*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,021*/ 1, 0x02, 
  /* RLE: 009 Pixels @ 039,021*/ 9, 0x00, 
  /* RLE: 019 Pixels @ 005,022*/ 19, 0x01, 
  /* ABS: 002 Pixels @ 024,022*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,022*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,022*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,022*/ 1, 0x02, 
  /* RLE: 011 Pixels @ 039,022*/ 11, 0x00, 
  /* RLE: 017 Pixels @ 007,023*/ 17, 0x01, 
  /* ABS: 002 Pixels @ 024,023*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,023*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,023*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,023*/ 1, 0x02, 
  /* RLE: 012 Pixels @ 039,023*/ 12, 0x00, 
  /* RLE: 016 Pixels @ 008,024*/ 16, 0x01, 
  /* ABS: 002 Pixels @ 024,024*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,024*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,024*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,024*/ 1, 0x02, 
  /* RLE: 012 Pixels @ 039,024*/ 12, 0x00, 
  /* RLE: 016 Pixels @ 008,025*/ 16, 0x01, 
  /* ABS: 002 Pixels @ 024,025*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,025*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,025*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,025*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 039,025*/ 14, 0x00, 
  /* RLE: 014 Pixels @ 010,026*/ 14, 0x01, 
  /* ABS: 002 Pixels @ 024,026*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,026*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,026*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,026*/ 1, 0x02, 
  /* RLE: 015 Pixels @ 039,026*/ 15, 0x00, 
  /* RLE: 013 Pixels @ 011,027*/ 13, 0x01, 
  /* ABS: 002 Pixels @ 024,027*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,027*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,027*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,027*/ 1, 0x02, 
  /* RLE: 015 Pixels @ 039,027*/ 15, 0x00, 
  /* RLE: 013 Pixels @ 011,028*/ 13, 0x01, 
  /* ABS: 002 Pixels @ 024,028*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,028*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,028*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,028*/ 1, 0x02, 
  /* RLE: 017 Pixels @ 039,028*/ 17, 0x00, 
  /* RLE: 011 Pixels @ 013,029*/ 11, 0x01, 
  /* ABS: 002 Pixels @ 024,029*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,029*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,029*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,029*/ 1, 0x02, 
  /* RLE: 017 Pixels @ 039,029*/ 17, 0x00, 
  /* RLE: 011 Pixels @ 013,030*/ 11, 0x01, 
  /* ABS: 002 Pixels @ 024,030*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,030*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,030*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,030*/ 1, 0x02, 
  /* RLE: 019 Pixels @ 039,030*/ 19, 0x00, 
  /* RLE: 009 Pixels @ 015,031*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 024,031*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,031*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,031*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,031*/ 1, 0x02, 
  /* RLE: 020 Pixels @ 039,031*/ 20, 0x00, 
  /* RLE: 008 Pixels @ 016,032*/ 8, 0x01, 
  /* ABS: 002 Pixels @ 024,032*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,032*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,032*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,032*/ 1, 0x02, 
  /* RLE: 020 Pixels @ 039,032*/ 20, 0x00, 
  /* RLE: 008 Pixels @ 016,033*/ 8, 0x01, 
  /* ABS: 002 Pixels @ 024,033*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,033*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,033*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,033*/ 1, 0x02, 
  /* RLE: 022 Pixels @ 039,033*/ 22, 0x00, 
  /* RLE: 006 Pixels @ 018,034*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 024,034*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,034*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,034*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,034*/ 1, 0x02, 
  /* RLE: 023 Pixels @ 039,034*/ 23, 0x00, 
  /* RLE: 005 Pixels @ 019,035*/ 5, 0x01, 
  /* ABS: 002 Pixels @ 024,035*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,035*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,035*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,035*/ 1, 0x02, 
  /* RLE: 023 Pixels @ 039,035*/ 23, 0x00, 
  /* RLE: 005 Pixels @ 019,036*/ 5, 0x01, 
  /* ABS: 002 Pixels @ 024,036*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,036*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,036*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,036*/ 1, 0x02, 
  /* RLE: 025 Pixels @ 039,036*/ 25, 0x00, 
  /* RLE: 003 Pixels @ 021,037*/ 3, 0x01, 
  /* ABS: 002 Pixels @ 024,037*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 026,037*/ 5, 0x00, 
  /* RLE: 007 Pixels @ 031,037*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 038,037*/ 1, 0x02, 
  /* RLE: 026 Pixels @ 039,037*/ 26, 0x00, 
  /* RLE: 004 Pixels @ 022,038*/ 4, 0x02, 
  /* RLE: 006 Pixels @ 026,038*/ 6, 0x00, 
  /* RLE: 007 Pixels @ 032,038*/ 7, 0x02, 
  /* RLE: 176 Pixels @ 039,038*/ 176, 0x00, 


  0};  /* 460 bytes for 1849 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmrewindbutton_S = {
  43, /* XSize */
  43, /* YSize */
  43, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acrewindbutton_S,  /* Pointer to picture data (indices) */
  &Palrewindbutton_S,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
