/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: forwardbutton_XS                                      *
* Dimensions:  29 * 29                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsforwardbutton_XS[] = {
     0xFFFFFF,0xFF0000,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palforwardbutton_XS = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsforwardbutton_XS[0]
};

static GUI_CONST_STORAGE unsigned char acforwardbutton_XS[] = {
  /* RLE: 120 Pixels @ 000,000*/ 120, 0x00, 
  /* RLE: 004 Pixels @ 004,004*/ 4, 0x01, 
  /* RLE: 005 Pixels @ 008,004*/ 5, 0x00, 
  /* RLE: 003 Pixels @ 013,004*/ 3, 0x01, 
  /* RLE: 017 Pixels @ 016,004*/ 17, 0x00, 
  /* RLE: 004 Pixels @ 004,005*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,005*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,005*/ 4, 0x00, 
  /* RLE: 004 Pixels @ 013,005*/ 4, 0x01, 
  /* RLE: 016 Pixels @ 017,005*/ 16, 0x00, 
  /* RLE: 004 Pixels @ 004,006*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,006*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,006*/ 4, 0x00, 
  /* RLE: 004 Pixels @ 013,006*/ 4, 0x01, 
  /* RLE: 016 Pixels @ 017,006*/ 16, 0x00, 
  /* RLE: 004 Pixels @ 004,007*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,007*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,007*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 013,007*/ 5, 0x01, 
  /* RLE: 015 Pixels @ 018,007*/ 15, 0x00, 
  /* RLE: 004 Pixels @ 004,008*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,008*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,008*/ 4, 0x00, 
  /* RLE: 007 Pixels @ 013,008*/ 7, 0x01, 
  /* RLE: 013 Pixels @ 020,008*/ 13, 0x00, 
  /* RLE: 004 Pixels @ 004,009*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,009*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,009*/ 4, 0x00, 
  /* RLE: 008 Pixels @ 013,009*/ 8, 0x01, 
  /* RLE: 012 Pixels @ 021,009*/ 12, 0x00, 
  /* RLE: 004 Pixels @ 004,010*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,010*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,010*/ 4, 0x00, 
  /* RLE: 009 Pixels @ 013,010*/ 9, 0x01, 
  /* RLE: 011 Pixels @ 022,010*/ 11, 0x00, 
  /* RLE: 004 Pixels @ 004,011*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,011*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,011*/ 4, 0x00, 
  /* RLE: 010 Pixels @ 013,011*/ 10, 0x01, 
  /* RLE: 010 Pixels @ 023,011*/ 10, 0x00, 
  /* RLE: 004 Pixels @ 004,012*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,012*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,012*/ 4, 0x00, 
  /* RLE: 011 Pixels @ 013,012*/ 11, 0x01, 
  /* RLE: 009 Pixels @ 024,012*/ 9, 0x00, 
  /* RLE: 004 Pixels @ 004,013*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,013*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,013*/ 4, 0x00, 
  /* RLE: 012 Pixels @ 013,013*/ 12, 0x01, 
  /* RLE: 008 Pixels @ 025,013*/ 8, 0x00, 
  /* RLE: 004 Pixels @ 004,014*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,014*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,014*/ 4, 0x00, 
  /* RLE: 013 Pixels @ 013,014*/ 13, 0x01, 
  /* RLE: 007 Pixels @ 026,014*/ 7, 0x00, 
  /* RLE: 004 Pixels @ 004,015*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,015*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,015*/ 4, 0x00, 
  /* RLE: 013 Pixels @ 013,015*/ 13, 0x01, 
  /* RLE: 001 Pixels @ 026,015*/ 1, 0x02, 
  /* RLE: 006 Pixels @ 027,015*/ 6, 0x00, 
  /* RLE: 004 Pixels @ 004,016*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,016*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,016*/ 4, 0x00, 
  /* RLE: 012 Pixels @ 013,016*/ 12, 0x01, 
  /* ABS: 002 Pixels @ 025,016*/ 0, 2, 0x02, 0x02, 
  /* RLE: 006 Pixels @ 027,016*/ 6, 0x00, 
  /* RLE: 004 Pixels @ 004,017*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,017*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,017*/ 4, 0x00, 
  /* RLE: 010 Pixels @ 013,017*/ 10, 0x01, 
  /* ABS: 002 Pixels @ 023,017*/ 0, 2, 0x02, 0x02, 
  /* RLE: 008 Pixels @ 025,017*/ 8, 0x00, 
  /* RLE: 004 Pixels @ 004,018*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,018*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,018*/ 4, 0x00, 
  /* RLE: 009 Pixels @ 013,018*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 022,018*/ 0, 2, 0x02, 0x02, 
  /* RLE: 009 Pixels @ 024,018*/ 9, 0x00, 
  /* RLE: 004 Pixels @ 004,019*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,019*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,019*/ 4, 0x00, 
  /* RLE: 008 Pixels @ 013,019*/ 8, 0x01, 
  /* ABS: 002 Pixels @ 021,019*/ 0, 2, 0x02, 0x02, 
  /* RLE: 010 Pixels @ 023,019*/ 10, 0x00, 
  /* RLE: 004 Pixels @ 004,020*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,020*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,020*/ 4, 0x00, 
  /* RLE: 007 Pixels @ 013,020*/ 7, 0x01, 
  /* ABS: 002 Pixels @ 020,020*/ 0, 2, 0x02, 0x02, 
  /* RLE: 011 Pixels @ 022,020*/ 11, 0x00, 
  /* RLE: 004 Pixels @ 004,021*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,021*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,021*/ 4, 0x00, 
  /* RLE: 006 Pixels @ 013,021*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 019,021*/ 0, 2, 0x02, 0x02, 
  /* RLE: 012 Pixels @ 021,021*/ 12, 0x00, 
  /* RLE: 004 Pixels @ 004,022*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,022*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,022*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 013,022*/ 5, 0x01, 
  /* ABS: 002 Pixels @ 018,022*/ 0, 2, 0x02, 0x02, 
  /* RLE: 013 Pixels @ 020,022*/ 13, 0x00, 
  /* RLE: 004 Pixels @ 004,023*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,023*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,023*/ 4, 0x00, 
  /* RLE: 004 Pixels @ 013,023*/ 4, 0x01, 
  /* ABS: 002 Pixels @ 017,023*/ 0, 2, 0x02, 0x02, 
  /* RLE: 014 Pixels @ 019,023*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 004,024*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,024*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,024*/ 4, 0x00, 
  /* RLE: 004 Pixels @ 013,024*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 017,024*/ 1, 0x02, 
  /* RLE: 015 Pixels @ 018,024*/ 15, 0x00, 
  /* RLE: 004 Pixels @ 004,025*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 008,025*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 009,025*/ 4, 0x00, 
  /* RLE: 003 Pixels @ 013,025*/ 3, 0x01, 
  /* RLE: 001 Pixels @ 016,025*/ 1, 0x02, 
  /* RLE: 017 Pixels @ 017,025*/ 17, 0x00, 
  /* RLE: 004 Pixels @ 005,026*/ 4, 0x02, 
  /* RLE: 005 Pixels @ 009,026*/ 5, 0x00, 
  /* RLE: 003 Pixels @ 014,026*/ 3, 0x02, 
  /* RLE: 070 Pixels @ 017,026*/ 70, 0x00, 


  0};  /* 266 bytes for 841 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmforwardbutton_XS = {
  29, /* XSize */
  29, /* YSize */
  29, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acforwardbutton_XS,  /* Pointer to picture data (indices) */
  &Palforwardbutton_XS,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
