/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: pausebutton_XS                                        *
* Dimensions:  29 * 29                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorspausebutton_XS[] = {
     0xFFFFFF,0x00F6FF,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palpausebutton_XS = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorspausebutton_XS[0]
};

static GUI_CONST_STORAGE unsigned char acpausebutton_XS[] = {
  /* RLE: 124 Pixels @ 000,000*/ 124, 0x00, 
  /* RLE: 004 Pixels @ 008,004*/ 4, 0x01, 
  /* RLE: 005 Pixels @ 012,004*/ 5, 0x00, 
  /* RLE: 005 Pixels @ 017,004*/ 5, 0x01, 
  /* RLE: 015 Pixels @ 022,004*/ 15, 0x00, 
  /* RLE: 004 Pixels @ 008,005*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,005*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,005*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,005*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,005*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,005*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,006*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,006*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,006*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,006*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,006*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,006*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,007*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,007*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,007*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,007*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,007*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,007*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,008*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,008*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,008*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,008*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,008*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,008*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,009*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,009*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,009*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,009*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,009*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,009*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,010*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,010*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,010*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,010*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,010*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,010*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,011*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,011*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,011*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,011*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,011*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,011*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,012*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,012*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,012*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,012*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,012*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,012*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,013*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,013*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,013*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,013*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,013*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,013*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,014*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,014*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,014*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,014*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,014*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,014*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,015*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,015*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,015*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,015*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,015*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,015*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,016*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,016*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,016*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,016*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,016*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,016*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,017*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,017*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,017*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,017*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,017*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,017*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,018*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,018*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,018*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,018*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,018*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,018*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,019*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,019*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,019*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,019*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,019*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,019*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,020*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,020*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,020*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,020*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,020*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,020*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,021*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,021*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,021*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,021*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,021*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,021*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,022*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,022*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,022*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,022*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,022*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,022*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,023*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,023*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,023*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,023*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,023*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,023*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,024*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,024*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,024*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,024*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,024*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,024*/ 14, 0x00, 
  /* RLE: 004 Pixels @ 008,025*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 012,025*/ 1, 0x02, 
  /* RLE: 004 Pixels @ 013,025*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 017,025*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 022,025*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 023,025*/ 14, 0x00, 
  /* RLE: 005 Pixels @ 008,026*/ 5, 0x02, 
  /* RLE: 005 Pixels @ 013,026*/ 5, 0x00, 
  /* RLE: 005 Pixels @ 018,026*/ 5, 0x02, 
  /* RLE: 064 Pixels @ 023,026*/ 64, 0x00, 


  0};  /* 270 bytes for 841 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmpausebutton_XS = {
  29, /* XSize */
  29, /* YSize */
  29, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acpausebutton_XS,  /* Pointer to picture data (indices) */
  &Palpausebutton_XS,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
