/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: playbutton_XS                                         *
* Dimensions:  29 * 29                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsplaybutton_XS[] = {
     0xFFFFFF,0x00FF00,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palplaybutton_XS = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsplaybutton_XS[0]
};

static GUI_CONST_STORAGE unsigned char acplaybutton_XS[] = {
  /* RLE: 125 Pixels @ 000,000*/ 125, 0x00, 
  /* RLE: 003 Pixels @ 009,004*/ 3, 0x01, 
  /* RLE: 026 Pixels @ 012,004*/ 26, 0x00, 
  /* RLE: 004 Pixels @ 009,005*/ 4, 0x01, 
  /* RLE: 025 Pixels @ 013,005*/ 25, 0x00, 
  /* RLE: 005 Pixels @ 009,006*/ 5, 0x01, 
  /* RLE: 024 Pixels @ 014,006*/ 24, 0x00, 
  /* RLE: 006 Pixels @ 009,007*/ 6, 0x01, 
  /* RLE: 023 Pixels @ 015,007*/ 23, 0x00, 
  /* RLE: 008 Pixels @ 009,008*/ 8, 0x01, 
  /* RLE: 021 Pixels @ 017,008*/ 21, 0x00, 
  /* RLE: 008 Pixels @ 009,009*/ 8, 0x01, 
  /* RLE: 021 Pixels @ 017,009*/ 21, 0x00, 
  /* RLE: 009 Pixels @ 009,010*/ 9, 0x01, 
  /* RLE: 020 Pixels @ 018,010*/ 20, 0x00, 
  /* RLE: 010 Pixels @ 009,011*/ 10, 0x01, 
  /* RLE: 019 Pixels @ 019,011*/ 19, 0x00, 
  /* RLE: 011 Pixels @ 009,012*/ 11, 0x01, 
  /* RLE: 018 Pixels @ 020,012*/ 18, 0x00, 
  /* RLE: 012 Pixels @ 009,013*/ 12, 0x01, 
  /* RLE: 017 Pixels @ 021,013*/ 17, 0x00, 
  /* RLE: 013 Pixels @ 009,014*/ 13, 0x01, 
  /* RLE: 016 Pixels @ 022,014*/ 16, 0x00, 
  /* RLE: 013 Pixels @ 009,015*/ 13, 0x01, 
  /* RLE: 001 Pixels @ 022,015*/ 1, 0x02, 
  /* RLE: 015 Pixels @ 023,015*/ 15, 0x00, 
  /* RLE: 012 Pixels @ 009,016*/ 12, 0x01, 
  /* ABS: 002 Pixels @ 021,016*/ 0, 2, 0x02, 0x02, 
  /* RLE: 015 Pixels @ 023,016*/ 15, 0x00, 
  /* RLE: 010 Pixels @ 009,017*/ 10, 0x01, 
  /* ABS: 002 Pixels @ 019,017*/ 0, 2, 0x02, 0x02, 
  /* RLE: 017 Pixels @ 021,017*/ 17, 0x00, 
  /* RLE: 009 Pixels @ 009,018*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 018,018*/ 0, 2, 0x02, 0x02, 
  /* RLE: 018 Pixels @ 020,018*/ 18, 0x00, 
  /* RLE: 008 Pixels @ 009,019*/ 8, 0x01, 
  /* ABS: 002 Pixels @ 017,019*/ 0, 2, 0x02, 0x02, 
  /* RLE: 019 Pixels @ 019,019*/ 19, 0x00, 
  /* RLE: 008 Pixels @ 009,020*/ 8, 0x01, 
  /* RLE: 001 Pixels @ 017,020*/ 1, 0x02, 
  /* RLE: 020 Pixels @ 018,020*/ 20, 0x00, 
  /* RLE: 007 Pixels @ 009,021*/ 7, 0x01, 
  /* RLE: 001 Pixels @ 016,021*/ 1, 0x02, 
  /* RLE: 021 Pixels @ 017,021*/ 21, 0x00, 
  /* RLE: 006 Pixels @ 009,022*/ 6, 0x01, 
  /* ABS: 002 Pixels @ 015,022*/ 0, 2, 0x02, 0x02, 
  /* RLE: 021 Pixels @ 017,022*/ 21, 0x00, 
  /* RLE: 005 Pixels @ 009,023*/ 5, 0x01, 
  /* ABS: 002 Pixels @ 014,023*/ 0, 2, 0x02, 0x02, 
  /* RLE: 022 Pixels @ 016,023*/ 22, 0x00, 
  /* RLE: 004 Pixels @ 009,024*/ 4, 0x01, 
  /* ABS: 002 Pixels @ 013,024*/ 0, 2, 0x02, 0x02, 
  /* RLE: 023 Pixels @ 015,024*/ 23, 0x00, 
  /* RLE: 003 Pixels @ 009,025*/ 3, 0x01, 
  /* ABS: 002 Pixels @ 012,025*/ 0, 2, 0x02, 0x02, 
  /* RLE: 025 Pixels @ 014,025*/ 25, 0x00, 
  /* RLE: 003 Pixels @ 010,026*/ 3, 0x02, 
  /* RLE: 074 Pixels @ 013,026*/ 74, 0x00, 


  0};  /* 132 bytes for 841 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmplaybutton_XS = {
  29, /* XSize */
  29, /* YSize */
  29, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acplaybutton_XS,  /* Pointer to picture data (indices) */
  &Palplaybutton_XS,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
