/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: rewindbutton_XS                                       *
* Dimensions:  29 * 29                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsrewindbutton_XS[] = {
     0xFFFFFF,0xFF0000,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palrewindbutton_XS = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsrewindbutton_XS[0]
};

static GUI_CONST_STORAGE unsigned char acrewindbutton_XS[] = {
  /* RLE: 130 Pixels @ 000,000*/ 130, 0x00, 
  /* RLE: 003 Pixels @ 014,004*/ 3, 0x01, 
  /* RLE: 004 Pixels @ 017,004*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,004*/ 5, 0x01, 
  /* RLE: 016 Pixels @ 026,004*/ 16, 0x00, 
  /* RLE: 004 Pixels @ 013,005*/ 4, 0x01, 
  /* RLE: 004 Pixels @ 017,005*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,005*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,005*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 027,005*/ 14, 0x00, 
  /* RLE: 005 Pixels @ 012,006*/ 5, 0x01, 
  /* RLE: 004 Pixels @ 017,006*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,006*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,006*/ 1, 0x02, 
  /* RLE: 013 Pixels @ 027,006*/ 13, 0x00, 
  /* RLE: 006 Pixels @ 011,007*/ 6, 0x01, 
  /* RLE: 004 Pixels @ 017,007*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,007*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,007*/ 1, 0x02, 
  /* RLE: 011 Pixels @ 027,007*/ 11, 0x00, 
  /* RLE: 008 Pixels @ 009,008*/ 8, 0x01, 
  /* RLE: 004 Pixels @ 017,008*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,008*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,008*/ 1, 0x02, 
  /* RLE: 010 Pixels @ 027,008*/ 10, 0x00, 
  /* RLE: 009 Pixels @ 008,009*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 017,009*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,009*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,009*/ 1, 0x02, 
  /* RLE: 010 Pixels @ 027,009*/ 10, 0x00, 
  /* RLE: 009 Pixels @ 008,010*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 017,010*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,010*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,010*/ 1, 0x02, 
  /* RLE: 009 Pixels @ 027,010*/ 9, 0x00, 
  /* RLE: 010 Pixels @ 007,011*/ 10, 0x01, 
  /* RLE: 004 Pixels @ 017,011*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,011*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,011*/ 1, 0x02, 
  /* RLE: 008 Pixels @ 027,011*/ 8, 0x00, 
  /* RLE: 011 Pixels @ 006,012*/ 11, 0x01, 
  /* RLE: 004 Pixels @ 017,012*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,012*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,012*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 027,012*/ 7, 0x00, 
  /* RLE: 012 Pixels @ 005,013*/ 12, 0x01, 
  /* RLE: 004 Pixels @ 017,013*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,013*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,013*/ 1, 0x02, 
  /* RLE: 006 Pixels @ 027,013*/ 6, 0x00, 
  /* RLE: 013 Pixels @ 004,014*/ 13, 0x01, 
  /* RLE: 004 Pixels @ 017,014*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,014*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,014*/ 1, 0x02, 
  /* RLE: 006 Pixels @ 027,014*/ 6, 0x00, 
  /* RLE: 013 Pixels @ 004,015*/ 13, 0x01, 
  /* RLE: 004 Pixels @ 017,015*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,015*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,015*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 027,015*/ 7, 0x00, 
  /* RLE: 012 Pixels @ 005,016*/ 12, 0x01, 
  /* RLE: 004 Pixels @ 017,016*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,016*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,016*/ 1, 0x02, 
  /* RLE: 009 Pixels @ 027,016*/ 9, 0x00, 
  /* RLE: 010 Pixels @ 007,017*/ 10, 0x01, 
  /* RLE: 004 Pixels @ 017,017*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,017*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,017*/ 1, 0x02, 
  /* RLE: 010 Pixels @ 027,017*/ 10, 0x00, 
  /* RLE: 009 Pixels @ 008,018*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 017,018*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,018*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,018*/ 1, 0x02, 
  /* RLE: 010 Pixels @ 027,018*/ 10, 0x00, 
  /* RLE: 009 Pixels @ 008,019*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 017,019*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,019*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,019*/ 1, 0x02, 
  /* RLE: 011 Pixels @ 027,019*/ 11, 0x00, 
  /* RLE: 008 Pixels @ 009,020*/ 8, 0x01, 
  /* RLE: 004 Pixels @ 017,020*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,020*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,020*/ 1, 0x02, 
  /* RLE: 012 Pixels @ 027,020*/ 12, 0x00, 
  /* RLE: 007 Pixels @ 010,021*/ 7, 0x01, 
  /* RLE: 004 Pixels @ 017,021*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,021*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,021*/ 1, 0x02, 
  /* RLE: 013 Pixels @ 027,021*/ 13, 0x00, 
  /* RLE: 006 Pixels @ 011,022*/ 6, 0x01, 
  /* RLE: 004 Pixels @ 017,022*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,022*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,022*/ 1, 0x02, 
  /* RLE: 014 Pixels @ 027,022*/ 14, 0x00, 
  /* RLE: 005 Pixels @ 012,023*/ 5, 0x01, 
  /* RLE: 004 Pixels @ 017,023*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,023*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,023*/ 1, 0x02, 
  /* RLE: 015 Pixels @ 027,023*/ 15, 0x00, 
  /* RLE: 004 Pixels @ 013,024*/ 4, 0x01, 
  /* RLE: 004 Pixels @ 017,024*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,024*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,024*/ 1, 0x02, 
  /* RLE: 016 Pixels @ 027,024*/ 16, 0x00, 
  /* RLE: 003 Pixels @ 014,025*/ 3, 0x01, 
  /* RLE: 004 Pixels @ 017,025*/ 4, 0x00, 
  /* RLE: 005 Pixels @ 021,025*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 026,025*/ 1, 0x02, 
  /* RLE: 017 Pixels @ 027,025*/ 17, 0x00, 
  /* ABS: 002 Pixels @ 015,026*/ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 017,026*/ 5, 0x00, 
  /* RLE: 005 Pixels @ 022,026*/ 5, 0x02, 
  /* RLE: 060 Pixels @ 027,026*/ 60, 0x00, 


  0};  /* 230 bytes for 841 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmrewindbutton_XS = {
  29, /* XSize */
  29, /* YSize */
  29, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acrewindbutton_XS,  /* Pointer to picture data (indices) */
  &Palrewindbutton_XS,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
