#define BUILD_NUMBER        2
#define BUILD_DATE          "5/31/2011"

#define COMPILER_TYPE       RowleyARM
#define UEZ_PROCESSOR       NXP_LPC1788


#define UEZ_DEFAULT_LCD_CONFIG              LCD_CONFIG_SHARP_LQ043T3DG01

#define PROCESSOR_OSCILLATOR_FREQUENCY      120000000
