#ifndef _PICTUREFRAMEGRAPHICS_H_
#define _PICTUREFRAMEGRAPHICS_H_

extern GUI_CONST_STORAGE GUI_BITMAP bmsettings;
extern GUI_CONST_STORAGE GUI_BITMAP bmforwardbutton;
extern GUI_CONST_STORAGE GUI_BITMAP bmpausebutton;
extern GUI_CONST_STORAGE GUI_BITMAP bmplaybutton;
extern GUI_CONST_STORAGE GUI_BITMAP bmrewindbutton;

extern GUI_CONST_STORAGE GUI_BITMAP bmsettings_M;
extern GUI_CONST_STORAGE GUI_BITMAP bmforwardbutton_M;
extern GUI_CONST_STORAGE GUI_BITMAP bmpausebutton_M;
extern GUI_CONST_STORAGE GUI_BITMAP bmplaybutton_M;
extern GUI_CONST_STORAGE GUI_BITMAP bmrewindbutton_M;

extern GUI_CONST_STORAGE GUI_BITMAP bmsettings_S;
extern GUI_CONST_STORAGE GUI_BITMAP bmforwardbutton_S;
extern GUI_CONST_STORAGE GUI_BITMAP bmpausebutton_S;
extern GUI_CONST_STORAGE GUI_BITMAP bmplaybutton_S;
extern GUI_CONST_STORAGE GUI_BITMAP bmrewindbutton_S;

extern GUI_CONST_STORAGE GUI_BITMAP bmsettings_XS;
extern GUI_CONST_STORAGE GUI_BITMAP bmforwardbutton_XS;
extern GUI_CONST_STORAGE GUI_BITMAP bmpausebutton_XS;
extern GUI_CONST_STORAGE GUI_BITMAP bmplaybutton_XS;
extern GUI_CONST_STORAGE GUI_BITMAP bmrewindbutton_XS;

#endif
