/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Backspace                                             *
* Dimensions:  95 * 95                                               *
* NumColors:   131                                                   *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsBackspace[] = {
     0xFFFFFF,0x5F5F5F,0x46D6FF,0x00F2FF
    ,0xC3C3C3,0x45D6FF,0x01F2FF,0x04F1FF
    ,0x02F2FF,0x03F1FF,0x05F0FF,0x44D7FF
    ,0x40D8FF,0x41D8FF,0xCEC3C3,0xC3C3CE
    ,0xFEFFFF,0x11EBFF,0x0BEEFF,0x0DEDFF
    ,0x05F1FF,0x07F2FF,0x2EE0FF,0x43D7FF
    ,0x44D6FF,0x40D9FF,0xD7C3C3,0xFBFFFF
    ,0x2EDFFF,0x33DDFF,0x32DFFF,0x37DCFF
    ,0x39DBFF,0x3DD9FF,0x3FD9FF,0x3CDAFF
    ,0x38DCFF,0x10EBFF,0x12EBFF,0x10ECFF
    ,0x11ECFF,0x19E9FF,0x03F2FF,0x06F1FF
    ,0x07F1FF,0x05F2FF,0x0AF0FF,0x08F2FF
    ,0x0AF2FF,0x0BF2FF,0x45D7FF,0xE1CEC3
    ,0xECD7C3,0xFCFFFF,0xFDFFFF,0x2FDFFF
    ,0x37DBFF,0x30DEFF,0x31DEFF,0x30DFFF
    ,0x32DEFF,0x33DEFF,0x34DDFF,0x35DDFF
    ,0x36DCFF,0x34DEFF,0x38DBFF,0x3ADAFF
    ,0x3BDAFF,0x3ADBFF,0x3CD9FF,0x3ED8FF
    ,0x3FD8FF,0x3ED9FF,0x3DDBFF,0x3EDAFF
    ,0x07EFFF,0x0BEDFF,0x09EFFF,0x0AEEFF
    ,0x0AEFFF,0x0BEFFF,0x0DECFF,0x0EECFF
    ,0x0CEEFF,0x0EEEFF,0x0FEEFF,0x1BE7FF
    ,0x1EE6FF,0x1EE7FF,0x11EAFF,0x13EBFF
    ,0x14E9FF,0x15EAFF,0x16EAFF,0x16EBFF
    ,0x10EDFF,0x12ECFF,0x18E8FF,0x18E9FF
    ,0x1BE8FF,0x1AE9FF,0x02F1FF,0x04F0FF
    ,0x07F0FF,0x04F2FF,0x06F2FF,0x09F2FF
    ,0x0CF2FF,0x0DF2FF,0x0EF2FF,0x11F2FF
    ,0x12F2FF,0x23E5FF,0x28E2FF,0x2DE1FF
    ,0x2FE0FF,0x40D7FF,0x41D7FF,0x43D6FF
    ,0x46D6FE,0xC3CEE1,0xCDFCFF,0xE4FDFF
    ,0xE5FEFF,0xE7FEFF,0xE8FEFF,0xEFFFFF
    ,0xF0FEFF,0xF7FFFF,0xFAFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalBackspace = {
  131,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsBackspace[0]
};

static GUI_CONST_STORAGE unsigned char acBackspace[] = {
  /* RLE: 2027 Pixels @ 000,000*/ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 249, 0x00, 
  /* RLE: 057 Pixels @ 032,021*/ 57, 0x03, 
  /* RLE: 037 Pixels @ 089,021*/ 37, 0x00, 
  /* ABS: 004 Pixels @ 031,022*/ 0, 4, 0x03, 0x31, 0x09, 0x0A, 
  /* RLE: 054 Pixels @ 035,022*/ 54, 0x03, 
  /* RLE: 036 Pixels @ 089,022*/ 36, 0x00, 
  /* ABS: 005 Pixels @ 030,023*/ 0, 5, 0x03, 0x70, 0x14, 0x4E, 0x19, 
  /* RLE: 052 Pixels @ 035,023*/ 52, 0x02, 
  /* ABS: 002 Pixels @ 087,023*/ 0, 2, 0x03, 0x03, 
  /* RLE: 035 Pixels @ 089,023*/ 35, 0x00, 
  /* ABS: 005 Pixels @ 029,024*/ 0, 5, 0x03, 0x6B, 0x2C, 0x13, 0x45, 
  /* RLE: 053 Pixels @ 034,024*/ 53, 0x02, 
  /* ABS: 002 Pixels @ 087,024*/ 0, 2, 0x03, 0x03, 
  /* RLE: 034 Pixels @ 089,024*/ 34, 0x00, 
  /* ABS: 006 Pixels @ 028,025*/ 0, 6, 0x03, 0x08, 0x14, 0x5E, 0x3D, 0x05, 
  /* RLE: 053 Pixels @ 034,025*/ 53, 0x02, 
  /* ABS: 002 Pixels @ 087,025*/ 0, 2, 0x03, 0x03, 
  /* RLE: 033 Pixels @ 089,025*/ 33, 0x00, 
  /* ABS: 008 Pixels @ 027,026*/ 0, 8, 0x03, 0x15, 0x08, 0x13, 0x1C, 0x0B, 0x02, 0x02, 
  /* RLE: 049 Pixels @ 035,026*/ 49, 0x01, 
  /* RLE: 003 Pixels @ 084,026*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,026*/ 0, 2, 0x03, 0x03, 
  /* RLE: 032 Pixels @ 089,026*/ 32, 0x00, 
  /* ABS: 008 Pixels @ 026,027*/ 0, 8, 0x03, 0x30, 0x08, 0x25, 0x3E, 0x18, 0x02, 0x02, 
  /* RLE: 050 Pixels @ 034,027*/ 50, 0x01, 
  /* RLE: 003 Pixels @ 084,027*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,027*/ 0, 2, 0x03, 0x03, 
  /* RLE: 031 Pixels @ 089,027*/ 31, 0x00, 
  /* ABS: 008 Pixels @ 025,028*/ 0, 8, 0x03, 0x2D, 0x67, 0x5A, 0x1D, 0x05, 0x02, 0x02, 
  /* RLE: 051 Pixels @ 033,028*/ 51, 0x01, 
  /* RLE: 003 Pixels @ 084,028*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,028*/ 0, 2, 0x03, 0x03, 
  /* RLE: 030 Pixels @ 089,028*/ 30, 0x00, 
  /* ABS: 008 Pixels @ 024,029*/ 0, 8, 0x03, 0x08, 0x09, 0x11, 0x37, 0x0D, 0x02, 0x02, 
  /* RLE: 052 Pixels @ 032,029*/ 52, 0x01, 
  /* RLE: 003 Pixels @ 084,029*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,029*/ 0, 2, 0x03, 0x03, 
  /* RLE: 029 Pixels @ 089,029*/ 29, 0x00, 
  /* ABS: 008 Pixels @ 023,030*/ 0, 8, 0x03, 0x30, 0x4C, 0x28, 0x74, 0x76, 0x02, 0x02, 
  /* RLE: 053 Pixels @ 031,030*/ 53, 0x01, 
  /* RLE: 003 Pixels @ 084,030*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,030*/ 0, 2, 0x03, 0x03, 
  /* RLE: 028 Pixels @ 089,030*/ 28, 0x00, 
  /* ABS: 008 Pixels @ 022,031*/ 0, 8, 0x03, 0x6F, 0x07, 0x5C, 0x1E, 0x0C, 0x02, 0x02, 
  /* RLE: 054 Pixels @ 030,031*/ 54, 0x01, 
  /* RLE: 003 Pixels @ 084,031*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,031*/ 0, 2, 0x03, 0x03, 
  /* RLE: 027 Pixels @ 089,031*/ 27, 0x00, 
  /* ABS: 008 Pixels @ 021,032*/ 0, 8, 0x03, 0x6C, 0x07, 0x26, 0x43, 0x05, 0x02, 0x02, 
  /* RLE: 055 Pixels @ 029,032*/ 55, 0x01, 
  /* RLE: 003 Pixels @ 084,032*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,032*/ 0, 2, 0x03, 0x03, 
  /* RLE: 026 Pixels @ 089,032*/ 26, 0x00, 
  /* ABS: 008 Pixels @ 020,033*/ 0, 8, 0x03, 0x2D, 0x2B, 0x29, 0x4A, 0x02, 0x02, 0x78, 
  /* RLE: 056 Pixels @ 028,033*/ 56, 0x01, 
  /* RLE: 003 Pixels @ 084,033*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,033*/ 0, 2, 0x03, 0x03, 
  /* RLE: 025 Pixels @ 089,033*/ 25, 0x00, 
  /* ABS: 008 Pixels @ 019,034*/ 0, 8, 0x03, 0x6A, 0x0A, 0x58, 0x41, 0x02, 0x02, 0x02, 
  /* RLE: 057 Pixels @ 027,034*/ 57, 0x01, 
  /* RLE: 003 Pixels @ 084,034*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,034*/ 0, 2, 0x03, 0x03, 
  /* RLE: 024 Pixels @ 089,034*/ 24, 0x00, 
  /* ABS: 008 Pixels @ 018,035*/ 0, 8, 0x03, 0x2F, 0x14, 0x57, 0x20, 0x02, 0x02, 0x02, 
  /* RLE: 028 Pixels @ 026,035*/ 28, 0x01, 
  /* RLE: 003 Pixels @ 054,035*/ 3, 0x04, 
  /* ABS: 002 Pixels @ 057,035*/ 0, 2, 0x0E, 0x04, 
  /* RLE: 008 Pixels @ 059,035*/ 8, 0x01, 
  /* RLE: 004 Pixels @ 067,035*/ 4, 0x04, 
  /* RLE: 013 Pixels @ 071,035*/ 13, 0x01, 
  /* RLE: 003 Pixels @ 084,035*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,035*/ 0, 2, 0x03, 0x03, 
  /* RLE: 023 Pixels @ 089,035*/ 23, 0x00, 
  /* ABS: 008 Pixels @ 017,036*/ 0, 8, 0x03, 0x2F, 0x06, 0x11, 0x4B, 0x02, 0x02, 0x02, 
  /* RLE: 029 Pixels @ 025,036*/ 29, 0x01, 
  /* ABS: 006 Pixels @ 054,036*/ 0, 6, 0x04, 0x04, 0x0F, 0x04, 0x04, 0x04, 
  /* RLE: 006 Pixels @ 060,036*/ 6, 0x01, 
  /* RLE: 003 Pixels @ 066,036*/ 3, 0x04, 
  /* RLE: 001 Pixels @ 069,036*/ 1, 0x34, 
  /* RLE: 014 Pixels @ 070,036*/ 14, 0x01, 
  /* RLE: 003 Pixels @ 084,036*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,036*/ 0, 2, 0x03, 0x03, 
  /* RLE: 022 Pixels @ 089,036*/ 22, 0x00, 
  /* ABS: 008 Pixels @ 016,037*/ 0, 8, 0x03, 0x6D, 0x07, 0x53, 0x0D, 0x02, 0x02, 0x02, 
  /* RLE: 031 Pixels @ 024,037*/ 31, 0x01, 
  /* RLE: 003 Pixels @ 055,037*/ 3, 0x04, 
  /* ABS: 002 Pixels @ 058,037*/ 0, 2, 0x0E, 0x04, 
  /* RLE: 005 Pixels @ 060,037*/ 5, 0x01, 
  /* RLE: 003 Pixels @ 065,037*/ 3, 0x04, 
  /* ABS: 002 Pixels @ 068,037*/ 0, 2, 0x1A, 0x04, 
  /* RLE: 014 Pixels @ 070,037*/ 14, 0x01, 
  /* RLE: 003 Pixels @ 084,037*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,037*/ 0, 2, 0x03, 0x03, 
  /* RLE: 021 Pixels @ 089,037*/ 21, 0x00, 
  /* ABS: 008 Pixels @ 015,038*/ 0, 8, 0x03, 0x6E, 0x07, 0x52, 0x3F, 0x02, 0x02, 0x02, 
  /* RLE: 033 Pixels @ 023,038*/ 33, 0x01, 
  /* RLE: 005 Pixels @ 056,038*/ 5, 0x04, 
  /* RLE: 004 Pixels @ 061,038*/ 4, 0x01, 
  /* RLE: 004 Pixels @ 065,038*/ 4, 0x04, 
  /* RLE: 015 Pixels @ 069,038*/ 15, 0x01, 
  /* RLE: 003 Pixels @ 084,038*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,038*/ 0, 2, 0x03, 0x03, 
  /* RLE: 020 Pixels @ 089,038*/ 20, 0x00, 
  /* ABS: 008 Pixels @ 014,039*/ 0, 8, 0x03, 0x15, 0x0A, 0x5D, 0x3C, 0x05, 0x02, 0x02, 
  /* RLE: 035 Pixels @ 022,039*/ 35, 0x01, 
  /* RLE: 004 Pixels @ 057,039*/ 4, 0x04, 
  /* RLE: 003 Pixels @ 061,039*/ 3, 0x01, 
  /* RLE: 003 Pixels @ 064,039*/ 3, 0x04, 
  /* ABS: 002 Pixels @ 067,039*/ 0, 2, 0x33, 0x04, 
  /* RLE: 015 Pixels @ 069,039*/ 15, 0x01, 
  /* RLE: 003 Pixels @ 084,039*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,039*/ 0, 2, 0x03, 0x03, 
  /* RLE: 019 Pixels @ 089,039*/ 19, 0x00, 
  /* ABS: 008 Pixels @ 013,040*/ 0, 8, 0x03, 0x06, 0x0A, 0x62, 0x22, 0x05, 0x02, 0x02, 
  /* RLE: 036 Pixels @ 021,040*/ 36, 0x01, 
  /* RLE: 005 Pixels @ 057,040*/ 5, 0x04, 
  /* ABS: 006 Pixels @ 062,040*/ 0, 6, 0x01, 0x01, 0x04, 0x04, 0x0E, 0x04, 
  /* RLE: 016 Pixels @ 068,040*/ 16, 0x01, 
  /* RLE: 003 Pixels @ 084,040*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,040*/ 0, 2, 0x03, 0x03, 
  /* RLE: 018 Pixels @ 089,040*/ 18, 0x00, 
  /* ABS: 008 Pixels @ 012,041*/ 0, 8, 0x03, 0x03, 0x06, 0x61, 0x0C, 0x02, 0x02, 0x02, 
  /* RLE: 038 Pixels @ 020,041*/ 38, 0x01, 
  /* ABS: 002 Pixels @ 058,041*/ 0, 2, 0x04, 0x0F, 
  /* RLE: 007 Pixels @ 060,041*/ 7, 0x04, 
  /* RLE: 017 Pixels @ 067,041*/ 17, 0x01, 
  /* RLE: 003 Pixels @ 084,041*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,041*/ 0, 2, 0x03, 0x03, 
  /* RLE: 017 Pixels @ 089,041*/ 17, 0x00, 
  /* ABS: 008 Pixels @ 011,042*/ 0, 8, 0x03, 0x08, 0x03, 0x4D, 0x1F, 0x02, 0x02, 0x02, 
  /* RLE: 039 Pixels @ 019,042*/ 39, 0x01, 
  /* RLE: 003 Pixels @ 058,042*/ 3, 0x04, 
  /* ABS: 006 Pixels @ 061,042*/ 0, 6, 0x1A, 0x04, 0x04, 0x04, 0x1A, 0x04, 
  /* RLE: 017 Pixels @ 067,042*/ 17, 0x01, 
  /* RLE: 003 Pixels @ 084,042*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,042*/ 0, 2, 0x03, 0x03, 
  /* RLE: 016 Pixels @ 089,042*/ 16, 0x00, 
  /* ABS: 008 Pixels @ 010,043*/ 0, 8, 0x03, 0x03, 0x06, 0x13, 0x3A, 0x05, 0x02, 0x02, 
  /* RLE: 041 Pixels @ 018,043*/ 41, 0x01, 
  /* RLE: 004 Pixels @ 059,043*/ 4, 0x04, 
  /* ABS: 003 Pixels @ 063,043*/ 0, 3, 0x0F, 0x04, 0x04, 
  /* RLE: 018 Pixels @ 066,043*/ 18, 0x01, 
  /* RLE: 003 Pixels @ 084,043*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,043*/ 0, 2, 0x03, 0x03, 
  /* RLE: 015 Pixels @ 089,043*/ 15, 0x00, 
  /* ABS: 008 Pixels @ 009,044*/ 0, 8, 0x03, 0x06, 0x03, 0x25, 0x16, 0x77, 0x02, 0x02, 
  /* RLE: 043 Pixels @ 017,044*/ 43, 0x01, 
  /* RLE: 005 Pixels @ 060,044*/ 5, 0x04, 
  /* RLE: 019 Pixels @ 065,044*/ 19, 0x01, 
  /* RLE: 003 Pixels @ 084,044*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,044*/ 0, 2, 0x03, 0x03, 
  /* RLE: 015 Pixels @ 089,044*/ 15, 0x00, 
  /* ABS: 007 Pixels @ 009,045*/ 0, 7, 0x03, 0x03, 0x12, 0x3B, 0x49, 0x02, 0x02, 
  /* RLE: 044 Pixels @ 016,045*/ 44, 0x01, 
  /* RLE: 005 Pixels @ 060,045*/ 5, 0x04, 
  /* RLE: 019 Pixels @ 065,045*/ 19, 0x01, 
  /* RLE: 003 Pixels @ 084,045*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,045*/ 0, 2, 0x03, 0x03, 
  /* RLE: 016 Pixels @ 089,045*/ 16, 0x00, 
  /* ABS: 007 Pixels @ 010,046*/ 0, 7, 0x03, 0x4F, 0x11, 0x46, 0x18, 0x02, 0x02, 
  /* RLE: 043 Pixels @ 017,046*/ 43, 0x01, 
  /* RLE: 006 Pixels @ 060,046*/ 6, 0x04, 
  /* RLE: 018 Pixels @ 066,046*/ 18, 0x01, 
  /* RLE: 003 Pixels @ 084,046*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,046*/ 0, 2, 0x03, 0x03, 
  /* RLE: 016 Pixels @ 089,046*/ 16, 0x00, 
  /* ABS: 008 Pixels @ 010,047*/ 0, 8, 0x36, 0x03, 0x07, 0x27, 0x1F, 0x02, 0x02, 0x02, 
  /* RLE: 041 Pixels @ 018,047*/ 41, 0x01, 
  /* RLE: 007 Pixels @ 059,047*/ 7, 0x04, 
  /* RLE: 018 Pixels @ 066,047*/ 18, 0x01, 
  /* RLE: 003 Pixels @ 084,047*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,047*/ 0, 2, 0x03, 0x03, 
  /* RLE: 018 Pixels @ 089,047*/ 18, 0x00, 
  /* ABS: 007 Pixels @ 012,048*/ 0, 7, 0x03, 0x06, 0x11, 0x48, 0x0B, 0x02, 0x02, 
  /* RLE: 039 Pixels @ 019,048*/ 39, 0x01, 
  /* RLE: 009 Pixels @ 058,048*/ 9, 0x04, 
  /* RLE: 017 Pixels @ 067,048*/ 17, 0x01, 
  /* RLE: 003 Pixels @ 084,048*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,048*/ 0, 2, 0x03, 0x03, 
  /* RLE: 019 Pixels @ 089,048*/ 19, 0x00, 
  /* ABS: 007 Pixels @ 013,049*/ 0, 7, 0x03, 0x06, 0x72, 0x21, 0x32, 0x02, 0x02, 
  /* RLE: 037 Pixels @ 020,049*/ 37, 0x01, 
  /* RLE: 003 Pixels @ 057,049*/ 3, 0x04, 
  /* ABS: 003 Pixels @ 060,049*/ 0, 3, 0x0E, 0x04, 0x01, 
  /* RLE: 004 Pixels @ 063,049*/ 4, 0x04, 
  /* RLE: 017 Pixels @ 067,049*/ 17, 0x01, 
  /* RLE: 003 Pixels @ 084,049*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,049*/ 0, 2, 0x03, 0x03, 
  /* RLE: 020 Pixels @ 089,049*/ 20, 0x00, 
  /* ABS: 007 Pixels @ 014,050*/ 0, 7, 0x03, 0x12, 0x71, 0x20, 0x0B, 0x02, 0x02, 
  /* RLE: 036 Pixels @ 021,050*/ 36, 0x01, 
  /* ABS: 007 Pixels @ 057,050*/ 0, 7, 0x04, 0x0F, 0x04, 0x04, 0x04, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 064,050*/ 4, 0x04, 
  /* RLE: 016 Pixels @ 068,050*/ 16, 0x01, 
  /* RLE: 003 Pixels @ 084,050*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,050*/ 0, 2, 0x03, 0x03, 
  /* RLE: 020 Pixels @ 089,050*/ 20, 0x00, 
  /* ABS: 008 Pixels @ 014,051*/ 0, 8, 0x10, 0x03, 0x2C, 0x65, 0x23, 0x17, 0x02, 0x02, 
  /* RLE: 035 Pixels @ 022,051*/ 35, 0x01, 
  /* RLE: 004 Pixels @ 057,051*/ 4, 0x04, 
  /* RLE: 003 Pixels @ 061,051*/ 3, 0x01, 
  /* RLE: 005 Pixels @ 064,051*/ 5, 0x04, 
  /* RLE: 015 Pixels @ 069,051*/ 15, 0x01, 
  /* RLE: 003 Pixels @ 084,051*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,051*/ 0, 2, 0x03, 0x03, 
  /* RLE: 021 Pixels @ 089,051*/ 21, 0x00, 
  /* ABS: 008 Pixels @ 015,052*/ 0, 8, 0x81, 0x03, 0x69, 0x55, 0x42, 0x18, 0x02, 0x02, 
  /* RLE: 033 Pixels @ 023,052*/ 33, 0x01, 
  /* RLE: 005 Pixels @ 056,052*/ 5, 0x04, 
  /* RLE: 004 Pixels @ 061,052*/ 4, 0x01, 
  /* RLE: 004 Pixels @ 065,052*/ 4, 0x04, 
  /* RLE: 015 Pixels @ 069,052*/ 15, 0x01, 
  /* RLE: 003 Pixels @ 084,052*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,052*/ 0, 2, 0x03, 0x03, 
  /* RLE: 022 Pixels @ 089,052*/ 22, 0x00, 
  /* ABS: 008 Pixels @ 016,053*/ 0, 8, 0x7F, 0x03, 0x31, 0x2E, 0x39, 0x17, 0x02, 0x02, 
  /* RLE: 031 Pixels @ 024,053*/ 31, 0x01, 
  /* RLE: 003 Pixels @ 055,053*/ 3, 0x04, 
  /* ABS: 002 Pixels @ 058,053*/ 0, 2, 0x33, 0x04, 
  /* RLE: 005 Pixels @ 060,053*/ 5, 0x01, 
  /* ABS: 005 Pixels @ 065,053*/ 0, 5, 0x04, 0x79, 0x04, 0x04, 0x04, 
  /* RLE: 014 Pixels @ 070,053*/ 14, 0x01, 
  /* RLE: 003 Pixels @ 084,053*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,053*/ 0, 2, 0x03, 0x03, 
  /* RLE: 023 Pixels @ 089,053*/ 23, 0x00, 
  /* ABS: 008 Pixels @ 017,054*/ 0, 8, 0x7A, 0x03, 0x15, 0x56, 0x24, 0x19, 0x02, 0x02, 
  /* RLE: 030 Pixels @ 025,054*/ 30, 0x01, 
  /* ABS: 005 Pixels @ 055,054*/ 0, 5, 0x04, 0x04, 0x0E, 0x04, 0x04, 
  /* RLE: 006 Pixels @ 060,054*/ 6, 0x01, 
  /* ABS: 004 Pixels @ 066,054*/ 0, 4, 0x04, 0x0F, 0x04, 0x34, 
  /* RLE: 014 Pixels @ 070,054*/ 14, 0x01, 
  /* RLE: 003 Pixels @ 084,054*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,054*/ 0, 2, 0x03, 0x03, 
  /* RLE: 023 Pixels @ 089,054*/ 23, 0x00, 
  /* ABS: 009 Pixels @ 017,055*/ 0, 9, 0x10, 0x7C, 0x03, 0x2B, 0x12, 0x1E, 0x75, 0x02, 0x02, 
  /* RLE: 058 Pixels @ 026,055*/ 58, 0x01, 
  /* RLE: 003 Pixels @ 084,055*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,055*/ 0, 2, 0x03, 0x03, 
  /* RLE: 025 Pixels @ 089,055*/ 25, 0x00, 
  /* ABS: 008 Pixels @ 019,056*/ 0, 8, 0x7D, 0x03, 0x2E, 0x5F, 0x16, 0x0D, 0x02, 0x02, 
  /* RLE: 057 Pixels @ 027,056*/ 57, 0x01, 
  /* RLE: 003 Pixels @ 084,056*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,056*/ 0, 2, 0x03, 0x03, 
  /* RLE: 026 Pixels @ 089,056*/ 26, 0x00, 
  /* ABS: 008 Pixels @ 020,057*/ 0, 8, 0x7E, 0x03, 0x07, 0x64, 0x40, 0x02, 0x02, 0x02, 
  /* RLE: 056 Pixels @ 028,057*/ 56, 0x01, 
  /* RLE: 003 Pixels @ 084,057*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,057*/ 0, 2, 0x03, 0x03, 
  /* RLE: 027 Pixels @ 089,057*/ 27, 0x00, 
  /* ABS: 008 Pixels @ 021,058*/ 0, 8, 0x7B, 0x03, 0x08, 0x26, 0x44, 0x02, 0x02, 0x02, 
  /* RLE: 055 Pixels @ 029,058*/ 55, 0x01, 
  /* RLE: 003 Pixels @ 084,058*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,058*/ 0, 2, 0x03, 0x03, 
  /* RLE: 028 Pixels @ 089,058*/ 28, 0x00, 
  /* ABS: 008 Pixels @ 022,059*/ 0, 8, 0x80, 0x03, 0x09, 0x29, 0x22, 0x05, 0x02, 0x02, 
  /* RLE: 054 Pixels @ 030,059*/ 54, 0x01, 
  /* RLE: 003 Pixels @ 084,059*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,059*/ 0, 2, 0x03, 0x03, 
  /* RLE: 029 Pixels @ 089,059*/ 29, 0x00, 
  /* ABS: 008 Pixels @ 023,060*/ 0, 8, 0x35, 0x03, 0x68, 0x59, 0x0C, 0x32, 0x02, 0x02, 
  /* RLE: 053 Pixels @ 031,060*/ 53, 0x01, 
  /* RLE: 003 Pixels @ 084,060*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,060*/ 0, 2, 0x03, 0x03, 
  /* RLE: 030 Pixels @ 089,060*/ 30, 0x00, 
  /* ABS: 008 Pixels @ 024,061*/ 0, 8, 0x36, 0x03, 0x07, 0x28, 0x0D, 0x05, 0x02, 0x02, 
  /* RLE: 052 Pixels @ 032,061*/ 52, 0x01, 
  /* RLE: 003 Pixels @ 084,061*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,061*/ 0, 2, 0x03, 0x03, 
  /* RLE: 031 Pixels @ 089,061*/ 31, 0x00, 
  /* ABS: 008 Pixels @ 025,062*/ 0, 8, 0x35, 0x03, 0x66, 0x60, 0x23, 0x17, 0x02, 0x02, 
  /* RLE: 051 Pixels @ 033,062*/ 51, 0x01, 
  /* RLE: 003 Pixels @ 084,062*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,062*/ 0, 2, 0x03, 0x03, 
  /* RLE: 032 Pixels @ 089,062*/ 32, 0x00, 
  /* ABS: 008 Pixels @ 026,063*/ 0, 8, 0x10, 0x03, 0x09, 0x51, 0x47, 0x0C, 0x02, 0x02, 
  /* RLE: 050 Pixels @ 034,063*/ 50, 0x01, 
  /* RLE: 003 Pixels @ 084,063*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,063*/ 0, 2, 0x03, 0x03, 
  /* RLE: 033 Pixels @ 089,063*/ 33, 0x00, 
  /* ABS: 008 Pixels @ 027,064*/ 0, 8, 0x1B, 0x03, 0x06, 0x54, 0x73, 0x21, 0x05, 0x02, 
  /* RLE: 049 Pixels @ 035,064*/ 49, 0x01, 
  /* RLE: 003 Pixels @ 084,064*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,064*/ 0, 2, 0x03, 0x03, 
  /* RLE: 034 Pixels @ 089,064*/ 34, 0x00, 
  /* ABS: 008 Pixels @ 028,065*/ 0, 8, 0x82, 0x03, 0x03, 0x63, 0x1C, 0x38, 0x02, 0x02, 
  /* RLE: 048 Pixels @ 036,065*/ 48, 0x01, 
  /* RLE: 003 Pixels @ 084,065*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,065*/ 0, 2, 0x03, 0x03, 
  /* RLE: 035 Pixels @ 089,065*/ 35, 0x00, 
  /* ABS: 008 Pixels @ 029,066*/ 0, 8, 0x1B, 0x03, 0x2A, 0x27, 0x16, 0x19, 0x05, 0x02, 
  /* RLE: 047 Pixels @ 037,066*/ 47, 0x01, 
  /* RLE: 003 Pixels @ 084,066*/ 3, 0x02, 
  /* ABS: 002 Pixels @ 087,066*/ 0, 2, 0x03, 0x03, 
  /* RLE: 036 Pixels @ 089,066*/ 36, 0x00, 
  /* ABS: 007 Pixels @ 030,067*/ 0, 7, 0x1B, 0x03, 0x2A, 0x0A, 0x1D, 0x0C, 0x0B, 
  /* RLE: 050 Pixels @ 037,067*/ 50, 0x02, 
  /* ABS: 002 Pixels @ 087,067*/ 0, 2, 0x03, 0x03, 
  /* RLE: 038 Pixels @ 089,067*/ 38, 0x00, 
  /* ABS: 005 Pixels @ 032,068*/ 0, 5, 0x03, 0x06, 0x5B, 0x24, 0x0B, 
  /* RLE: 050 Pixels @ 037,068*/ 50, 0x02, 
  /* ABS: 002 Pixels @ 087,068*/ 0, 2, 0x03, 0x03, 
  /* RLE: 038 Pixels @ 089,068*/ 38, 0x00, 
  /* ABS: 005 Pixels @ 032,069*/ 0, 5, 0x10, 0x03, 0x09, 0x50, 0x0D, 
  /* RLE: 050 Pixels @ 037,069*/ 50, 0x02, 
  /* ABS: 002 Pixels @ 087,069*/ 0, 2, 0x03, 0x03, 
  /* RLE: 039 Pixels @ 089,069*/ 39, 0x00, 
  /* RLE: 001 Pixels @ 033,070*/ 1, 0x10, 
  /* RLE: 055 Pixels @ 034,070*/ 55, 0x03, 
  /* RLE: 2286 Pixels @ 089,070*/ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 


  0};  /* 1160 bytes for 9025 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmBackspace = {
  95, /* XSize */
  95, /* YSize */
  95, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acBackspace,  /* Pointer to picture data (indices) */
  &PalBackspace,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
