/*********************************************************************
*            (c) 1998 - 2023 SEGGER Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (NXP) for emWin V6.32.                     *
*        Compiled Feb 16 2023, 09:23:17                              *
*                                                                    *
*        (c) 1998 - 2023 SEGGER Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Cancel                                                *
* Dimensions:  128 * 45                                              *
* NumColors:   4                                                     *
* NumBytes:    191                                                   *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmCancel;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsCancel[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0x202020, 0x414141, 0xFFFFFF
#else
  0xFF000000, 0xFF202020, 0xFF414141, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalCancel = {
  4,  // Number of entries
  1,  // Has transparency
  (const LCD_COLOR *)&_ColorsCancel[0]
};

static GUI_CONST_STORAGE unsigned char _acCancel[] = {
  /* RLE: 1815 Pixels @ 000,000 */ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 37, 0x00, 
  /* RLE: 004 Pixels @ 023,014 */ 4, 0x03, 
  /* RLE: 006 Pixels @ 027,014 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 033,014 */ 4, 0x03, 
  /* RLE: 115 Pixels @ 037,014 */ 115, 0x00, 
  /* RLE: 004 Pixels @ 024,015 */ 4, 0x03, 
  /* RLE: 004 Pixels @ 028,015 */ 4, 0x00, 
  /* RLE: 004 Pixels @ 032,015 */ 4, 0x03, 
  /* RLE: 117 Pixels @ 036,015 */ 117, 0x00, 
  /* RLE: 003 Pixels @ 025,016 */ 3, 0x03, 
  /* RLE: 004 Pixels @ 028,016 */ 4, 0x00, 
  /* RLE: 004 Pixels @ 032,016 */ 4, 0x03, 
  /* RLE: 117 Pixels @ 036,016 */ 117, 0x00, 
  /* RLE: 004 Pixels @ 025,017 */ 4, 0x03, 
  /* ABS: 002 Pixels @ 029,017 */ 0, 2, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 031,017 */ 4, 0x03, 
  /* RLE: 119 Pixels @ 035,017 */ 119, 0x00, 
  /* RLE: 004 Pixels @ 026,018 */ 4, 0x03, 
  /* ABS: 004 Pixels @ 030,018 */ 0, 4, 0x02, 0x03, 0x03, 0x03, 
  /* RLE: 120 Pixels @ 034,018 */ 120, 0x00, 
  /* RLE: 001 Pixels @ 026,019 */ 1, 0x01, 
  /* RLE: 007 Pixels @ 027,019 */ 7, 0x03, 
  /* RLE: 121 Pixels @ 034,019 */ 121, 0x00, 
  /* RLE: 006 Pixels @ 027,020 */ 6, 0x03, 
  /* RLE: 122 Pixels @ 033,020 */ 122, 0x00, 
  /* RLE: 006 Pixels @ 027,021 */ 6, 0x03, 
  /* RLE: 122 Pixels @ 033,021 */ 122, 0x00, 
  /* RLE: 007 Pixels @ 027,022 */ 7, 0x03, 
  /* RLE: 120 Pixels @ 034,022 */ 120, 0x00, 
  /* RLE: 008 Pixels @ 026,023 */ 8, 0x03, 
  /* RLE: 119 Pixels @ 034,023 */ 119, 0x00, 
  /* RLE: 004 Pixels @ 025,024 */ 4, 0x03, 
  /* ABS: 002 Pixels @ 029,024 */ 0, 2, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 031,024 */ 4, 0x03, 
  /* RLE: 118 Pixels @ 035,024 */ 118, 0x00, 
  /* RLE: 004 Pixels @ 025,025 */ 4, 0x03, 
  /* ABS: 002 Pixels @ 029,025 */ 0, 2, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 031,025 */ 5, 0x03, 
  /* RLE: 116 Pixels @ 036,025 */ 116, 0x00, 
  /* RLE: 004 Pixels @ 024,026 */ 4, 0x03, 
  /* RLE: 004 Pixels @ 028,026 */ 4, 0x00, 
  /* RLE: 004 Pixels @ 032,026 */ 4, 0x03, 
  /* RLE: 115 Pixels @ 036,026 */ 115, 0x00, 
  /* RLE: 004 Pixels @ 023,027 */ 4, 0x03, 
  /* RLE: 006 Pixels @ 027,027 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 033,027 */ 4, 0x03, 
  /* RLE: 113 Pixels @ 037,027 */ 113, 0x00, 
  /* RLE: 005 Pixels @ 022,028 */ 5, 0x03, 
  /* RLE: 006 Pixels @ 027,028 */ 6, 0x00, 
  /* RLE: 005 Pixels @ 033,028 */ 5, 0x03, 
  /* RLE: 2138 Pixels @ 038,028 */ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 106, 0x00, 
  0
};  // 143 bytes for 5760 pixels

GUI_CONST_STORAGE GUI_BITMAP bmCancel = {
  128, // xSize
  45, // ySize
  128, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (const unsigned char *)_acCancel,  // Pointer to picture data (indices)
  &_PalCancel,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
