/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Cancel                                                *
* Dimensions:  128 * 45                                              *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsCancel[] = {
     0x000000,0xFFFFFF,0x202020,0x414141
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalCancel = {
  4,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsCancel[0]
};

static GUI_CONST_STORAGE unsigned char acCancel[] = {
  /* RLE: 1815 Pixels @ 000,000*/ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 37, 0x00, 
  /* RLE: 004 Pixels @ 023,014*/ 4, 0x01, 
  /* RLE: 006 Pixels @ 027,014*/ 6, 0x00, 
  /* RLE: 004 Pixels @ 033,014*/ 4, 0x01, 
  /* RLE: 115 Pixels @ 037,014*/ 115, 0x00, 
  /* RLE: 004 Pixels @ 024,015*/ 4, 0x01, 
  /* RLE: 004 Pixels @ 028,015*/ 4, 0x00, 
  /* RLE: 004 Pixels @ 032,015*/ 4, 0x01, 
  /* RLE: 117 Pixels @ 036,015*/ 117, 0x00, 
  /* RLE: 003 Pixels @ 025,016*/ 3, 0x01, 
  /* RLE: 004 Pixels @ 028,016*/ 4, 0x00, 
  /* RLE: 004 Pixels @ 032,016*/ 4, 0x01, 
  /* RLE: 117 Pixels @ 036,016*/ 117, 0x00, 
  /* RLE: 004 Pixels @ 025,017*/ 4, 0x01, 
  /* ABS: 002 Pixels @ 029,017*/ 0, 2, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 031,017*/ 4, 0x01, 
  /* RLE: 119 Pixels @ 035,017*/ 119, 0x00, 
  /* RLE: 004 Pixels @ 026,018*/ 4, 0x01, 
  /* ABS: 004 Pixels @ 030,018*/ 0, 4, 0x03, 0x01, 0x01, 0x01, 
  /* RLE: 120 Pixels @ 034,018*/ 120, 0x00, 
  /* RLE: 001 Pixels @ 026,019*/ 1, 0x02, 
  /* RLE: 007 Pixels @ 027,019*/ 7, 0x01, 
  /* RLE: 121 Pixels @ 034,019*/ 121, 0x00, 
  /* RLE: 006 Pixels @ 027,020*/ 6, 0x01, 
  /* RLE: 122 Pixels @ 033,020*/ 122, 0x00, 
  /* RLE: 006 Pixels @ 027,021*/ 6, 0x01, 
  /* RLE: 122 Pixels @ 033,021*/ 122, 0x00, 
  /* RLE: 007 Pixels @ 027,022*/ 7, 0x01, 
  /* RLE: 120 Pixels @ 034,022*/ 120, 0x00, 
  /* RLE: 008 Pixels @ 026,023*/ 8, 0x01, 
  /* RLE: 119 Pixels @ 034,023*/ 119, 0x00, 
  /* RLE: 004 Pixels @ 025,024*/ 4, 0x01, 
  /* ABS: 002 Pixels @ 029,024*/ 0, 2, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 031,024*/ 4, 0x01, 
  /* RLE: 118 Pixels @ 035,024*/ 118, 0x00, 
  /* RLE: 004 Pixels @ 025,025*/ 4, 0x01, 
  /* ABS: 002 Pixels @ 029,025*/ 0, 2, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 031,025*/ 5, 0x01, 
  /* RLE: 116 Pixels @ 036,025*/ 116, 0x00, 
  /* RLE: 004 Pixels @ 024,026*/ 4, 0x01, 
  /* RLE: 004 Pixels @ 028,026*/ 4, 0x00, 
  /* RLE: 004 Pixels @ 032,026*/ 4, 0x01, 
  /* RLE: 115 Pixels @ 036,026*/ 115, 0x00, 
  /* RLE: 004 Pixels @ 023,027*/ 4, 0x01, 
  /* RLE: 006 Pixels @ 027,027*/ 6, 0x00, 
  /* RLE: 004 Pixels @ 033,027*/ 4, 0x01, 
  /* RLE: 113 Pixels @ 037,027*/ 113, 0x00, 
  /* RLE: 005 Pixels @ 022,028*/ 5, 0x01, 
  /* RLE: 006 Pixels @ 027,028*/ 6, 0x00, 
  /* RLE: 005 Pixels @ 033,028*/ 5, 0x01, 
  /* RLE: 2138 Pixels @ 038,028*/ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 106, 0x00, 


  0};  /* 142 bytes for 5760 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmCancel = {
  128, /* XSize */
  45, /* YSize */
  128, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acCancel,  /* Pointer to picture data (indices) */
  &PalCancel,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
