/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: KeypadKeyPressed                                      *
* Dimensions:  78 * 74                                               *
* NumColors:   21                                                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsKeypadKeyPressed[] = {
     0xFFFFFF,0x000000,0x747474,0x848484
    ,0x7D7D7D,0x7B7B7B,0x7A7A7A,0x7E7E7E
    ,0x808080,0x737373,0x797979,0x707070
    ,0x717171,0x727272,0x757575,0x787878
    ,0x7C7C7C,0x828282,0x858585,0x8A8A8A
    ,0x8D8D8D
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalKeypadKeyPressed = {
  21,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsKeypadKeyPressed[0]
};

static GUI_CONST_STORAGE unsigned char acKeypadKeyPressed[] = {
  /* ABS: 002 Pixels @ 000,000*/ 0, 2, 0x09, 0x0A, 
  /* RLE: 073 Pixels @ 002,000*/ 73, 0x02, 
  /* ABS: 005 Pixels @ 075,000*/ 0, 5, 0x0E, 0x10, 0x0C, 0x11, 0x13, 
  /* RLE: 073 Pixels @ 002,001*/ 73, 0x03, 
  /* ABS: 004 Pixels @ 075,001*/ 0, 4, 0x12, 0x14, 0x08, 0x04, 
  /* RLE: 076 Pixels @ 001,002*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,002*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,003*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,003*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,004*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,004*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,005*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,005*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,006*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,006*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,007*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,007*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,008*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,008*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,009*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,009*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,010*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,010*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,011*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,011*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,012*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,012*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,013*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,013*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,014*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,014*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,015*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,015*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,016*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,016*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,017*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,017*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,018*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,018*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,019*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,019*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,020*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,020*/ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 001,021*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,021*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,022*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,022*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,023*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,023*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,024*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,024*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,025*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,025*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,026*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,026*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,027*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,027*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,028*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,028*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,029*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,029*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,030*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,030*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,031*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,031*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,032*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,032*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,033*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,033*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,034*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,034*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,035*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,035*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,036*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,036*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,037*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,037*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,038*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,038*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,039*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,039*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,040*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,040*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,041*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,041*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,042*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,042*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,043*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,043*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,044*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,044*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,045*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,045*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,046*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,046*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,047*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,047*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,048*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,048*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,049*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,049*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,050*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,050*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,051*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,051*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,052*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,052*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,053*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,053*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,054*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,054*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,055*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,055*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,056*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,056*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,057*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,057*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,058*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,058*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,059*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,059*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,060*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,060*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,061*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,061*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,062*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,062*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,063*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,063*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,064*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,064*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,065*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,065*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,066*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,066*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,067*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,067*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,068*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,068*/ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 001,069*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,069*/ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 001,070*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,070*/ 0, 2, 0x05, 0x08, 
  /* RLE: 076 Pixels @ 001,071*/ 76, 0x01, 
  /* ABS: 002 Pixels @ 077,071*/ 0, 2, 0x07, 0x08, 
  /* RLE: 076 Pixels @ 001,072*/ 76, 0x01, 
  /* ABS: 003 Pixels @ 077,072*/ 0, 3, 0x04, 0x0D, 0x0F, 
  /* RLE: 073 Pixels @ 002,073*/ 73, 0x02, 
  /* ABS: 003 Pixels @ 075,073*/ 0, 3, 0x09, 0x0A, 0x0B, 


  0};  /* 455 bytes for 5772 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmKeypadKeyPressed = {
  78, /* XSize */
  74, /* YSize */
  78, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acKeypadKeyPressed,  /* Pointer to picture data (indices) */
  &PalKeypadKeyPressed,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
