/*********************************************************************
*            (c) 1998 - 2023 SEGGER Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (NXP) for emWin V6.32.                     *
*        Compiled Feb 16 2023, 09:23:17                              *
*                                                                    *
*        (c) 1998 - 2023 SEGGER Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: KeypadKeyPressed                                      *
* Dimensions:  78 * 74                                               *
* NumColors:   21                                                    *
* NumBytes:    572                                                   *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmKeypadKeyPressed;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsKeypadKeyPressed[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0x000000, 0x747474, 0x848484,
  0x7D7D7D, 0x7B7B7B, 0x7A7A7A, 0x7E7E7E,
  0x808080, 0x737373, 0x797979, 0x707070,
  0x717171, 0x727272, 0x757575, 0x787878,
  0x7C7C7C, 0x828282, 0x858585, 0x8A8A8A,
  0x8D8D8D
#else
  0xFF000000, 0xFF000000, 0xFF747474, 0xFF848484,
  0xFF7D7D7D, 0xFF7B7B7B, 0xFF7A7A7A, 0xFF7E7E7E,
  0xFF808080, 0xFF737373, 0xFF797979, 0xFF707070,
  0xFF717171, 0xFF727272, 0xFF757575, 0xFF787878,
  0xFF7C7C7C, 0xFF828282, 0xFF858585, 0xFF8A8A8A,
  0xFF8D8D8D
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalKeypadKeyPressed = {
  21,  // Number of entries
  1,   // Has transparency
  (const LCD_COLOR *)&_ColorsKeypadKeyPressed[0]
};

static GUI_CONST_STORAGE unsigned char _acKeypadKeyPressed[] = {
  /* ABS: 002 Pixels @ 00,00 */ 0, 2, 0x09, 0x0A, 
  /* RLE: 073 Pixels @ 02,00 */ 73, 0x02, 
  /* ABS: 005 Pixels @ 75,00 */ 0, 5, 0x0E, 0x10, 0x0C, 0x11, 0x13, 
  /* RLE: 073 Pixels @ 02,01 */ 73, 0x03, 
  /* ABS: 004 Pixels @ 75,01 */ 0, 4, 0x12, 0x14, 0x08, 0x04, 
  /* RLE: 076 Pixels @ 01,02 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,02 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,03 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,03 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,04 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,04 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,05 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,05 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,06 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,06 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,07 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,07 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,08 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,08 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,09 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,09 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,10 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,10 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,11 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,11 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,12 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,12 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,13 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,13 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,14 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,14 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,15 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,15 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,16 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,16 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,17 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,17 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,18 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,18 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,19 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,19 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,20 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,20 */ 0, 2, 0x06, 0x04, 
  /* RLE: 076 Pixels @ 01,21 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,21 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,22 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,22 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,23 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,23 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,24 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,24 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,25 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,25 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,26 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,26 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,27 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,27 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,28 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,28 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,29 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,29 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,30 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,30 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,31 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,31 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,32 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,32 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,33 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,33 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,34 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,34 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,35 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,35 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,36 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,36 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,37 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,37 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,38 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,38 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,39 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,39 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,40 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,40 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,41 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,41 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,42 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,42 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,43 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,43 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,44 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,44 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,45 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,45 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,46 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,46 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,47 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,47 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,48 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,48 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,49 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,49 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,50 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,50 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,51 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,51 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,52 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,52 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,53 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,53 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,54 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,54 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,55 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,55 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,56 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,56 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,57 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,57 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,58 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,58 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,59 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,59 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,60 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,60 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,61 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,61 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,62 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,62 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,63 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,63 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,64 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,64 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,65 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,65 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,66 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,66 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,67 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,67 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,68 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,68 */ 0, 2, 0x05, 0x07, 
  /* RLE: 076 Pixels @ 01,69 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,69 */ 0, 2, 0x05, 0x04, 
  /* RLE: 076 Pixels @ 01,70 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,70 */ 0, 2, 0x05, 0x08, 
  /* RLE: 076 Pixels @ 01,71 */ 76, 0x01, 
  /* ABS: 002 Pixels @ 77,71 */ 0, 2, 0x07, 0x08, 
  /* RLE: 076 Pixels @ 01,72 */ 76, 0x01, 
  /* ABS: 003 Pixels @ 77,72 */ 0, 3, 0x04, 0x0D, 0x0F, 
  /* RLE: 073 Pixels @ 02,73 */ 73, 0x02, 
  /* ABS: 003 Pixels @ 75,73 */ 0, 3, 0x09, 0x0A, 0x0B, 
  0
};  // 456 bytes for 5772 pixels

GUI_CONST_STORAGE GUI_BITMAP bmKeypadKeyPressed = {
  78, // xSize
  74, // ySize
  78, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (const unsigned char *)_acKeypadKeyPressed,  // Pointer to picture data (indices)
  &_PalKeypadKeyPressed,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
