/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: KeypadKey                                             *
* Dimensions:  78 * 74                                               *
* NumColors:   24                                                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsKeypadKey[] = {
     0x808080,0x7F7F7F,0x828282,0x747474
    ,0x848484,0x868686,0x7D7D7D,0x7B7B7B
    ,0x7A7A7A,0x7E7E7E,0x858585,0x878787
    ,0x737373,0x797979,0x838383,0x898989
    ,0x707070,0x717171,0x727272,0x757575
    ,0x787878,0x7C7C7C,0x8A8A8A,0x8D8D8D
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalKeypadKey = {
  24,	/* number of entries */
  0, 	/* No transparency */
  &ColorsKeypadKey[0]
};

static GUI_CONST_STORAGE unsigned char acKeypadKey[] = {
  /* ABS: 002 Pixels @ 000,000*/ 0, 2, 0x0C, 0x0D, 
  /* RLE: 073 Pixels @ 002,000*/ 73, 0x03, 
  /* ABS: 005 Pixels @ 075,000*/ 0, 5, 0x13, 0x15, 0x11, 0x02, 0x16, 
  /* RLE: 073 Pixels @ 002,001*/ 73, 0x04, 
  /* ABS: 005 Pixels @ 075,001*/ 0, 5, 0x0A, 0x17, 0x00, 0x06, 0x04, 
  /* RLE: 074 Pixels @ 002,002*/ 74, 0x01, 
  /* ABS: 005 Pixels @ 076,002*/ 0, 5, 0x0B, 0x07, 0x09, 0x0A, 0x01, 
  /* RLE: 069 Pixels @ 003,003*/ 69, 0x00, 
  /* ABS: 009 Pixels @ 072,003*/ 0, 9, 0x01, 0x00, 0x01, 0x01, 0x05, 0x08, 0x06, 0x0A, 0x01, 
  /* RLE: 069 Pixels @ 003,004*/ 69, 0x00, 
  /* ABS: 009 Pixels @ 072,004*/ 0, 9, 0x01, 0x00, 0x00, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 069 Pixels @ 003,005*/ 69, 0x00, 
  /* ABS: 009 Pixels @ 072,005*/ 0, 9, 0x01, 0x00, 0x00, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 070 Pixels @ 003,006*/ 70, 0x00, 
  /* RLE: 003 Pixels @ 073,006*/ 3, 0x01, 
  /* ABS: 005 Pixels @ 076,006*/ 0, 5, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,007*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,007*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,008*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,008*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,009*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,009*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,010*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,010*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,011*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,011*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,012*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,012*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,013*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,013*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,014*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,014*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,015*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,015*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,016*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,016*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,017*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,017*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,018*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,018*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,019*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,019*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,020*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,020*/ 0, 7, 0x01, 0x01, 0x05, 0x08, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,021*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,021*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,022*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,022*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,023*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,023*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,024*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,024*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,025*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,025*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,026*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,026*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,027*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,027*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,028*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,028*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,029*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,029*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,030*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,030*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,031*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,031*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,032*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,032*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,033*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,033*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,034*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,034*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,035*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,035*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,036*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,036*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,037*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,037*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,038*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,038*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,039*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,039*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,040*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,040*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,041*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,041*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,042*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,042*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,043*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,043*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,044*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,044*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,045*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,045*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,046*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,046*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,047*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,047*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,048*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,048*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,049*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,049*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,050*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,050*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,051*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,051*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,052*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,052*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,053*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,053*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,054*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,054*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,055*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,055*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,056*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,056*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,057*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,057*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x06, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,058*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,058*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,059*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,059*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,060*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,060*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,061*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,061*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,062*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,062*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,063*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,063*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,064*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,064*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,065*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,065*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,066*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,066*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 071 Pixels @ 003,067*/ 71, 0x00, 
  /* ABS: 007 Pixels @ 074,067*/ 0, 7, 0x01, 0x01, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 070 Pixels @ 003,068*/ 70, 0x00, 
  /* RLE: 003 Pixels @ 073,068*/ 3, 0x01, 
  /* ABS: 005 Pixels @ 076,068*/ 0, 5, 0x05, 0x07, 0x09, 0x04, 0x01, 
  /* RLE: 070 Pixels @ 003,069*/ 70, 0x00, 
  /* RLE: 003 Pixels @ 073,069*/ 3, 0x01, 
  /* ABS: 004 Pixels @ 076,069*/ 0, 4, 0x05, 0x07, 0x06, 0x04, 
  /* RLE: 071 Pixels @ 002,070*/ 71, 0x01, 
  /* RLE: 003 Pixels @ 073,070*/ 3, 0x00, 
  /* ABS: 004 Pixels @ 076,070*/ 0, 4, 0x05, 0x07, 0x00, 0x0B, 
  /* RLE: 072 Pixels @ 002,071*/ 72, 0x02, 
  /* ABS: 006 Pixels @ 074,071*/ 0, 6, 0x0E, 0x0E, 0x0F, 0x09, 0x00, 0x0B, 
  /* RLE: 074 Pixels @ 002,072*/ 74, 0x02, 
  /* ABS: 004 Pixels @ 076,072*/ 0, 4, 0x0F, 0x06, 0x12, 0x14, 
  /* RLE: 073 Pixels @ 002,073*/ 73, 0x03, 
  /* ABS: 003 Pixels @ 075,073*/ 0, 3, 0x0C, 0x0D, 0x10, 


  0};  /* 808 bytes for 5772 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmKeypadKey = {
  78, /* XSize */
  74, /* YSize */
  78, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acKeypadKey,  /* Pointer to picture data (indices) */
  &PalKeypadKey,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
