/*********************************************************************
*            (c) 1998 - 2023 SEGGER Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (NXP) for emWin V6.32.                     *
*        Compiled Feb 16 2023, 09:23:17                              *
*                                                                    *
*        (c) 1998 - 2023 SEGGER Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: KeypadKey                                             *
* Dimensions:  78 * 74                                               *
* NumColors:   25                                                    *
* NumBytes:    941                                                   *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmKeypadKey;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsKeypadKey[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0x808080, 0x7F7F7F, 0x828282,
  0x747474, 0x848484, 0x868686, 0x7D7D7D,
  0x7B7B7B, 0x7A7A7A, 0x7E7E7E, 0x858585,
  0x878787, 0x737373, 0x797979, 0x838383,
  0x898989, 0x707070, 0x717171, 0x727272,
  0x757575, 0x787878, 0x7C7C7C, 0x8A8A8A,
  0x8D8D8D
#else
  0xFF000000, 0xFF808080, 0xFF7F7F7F, 0xFF828282,
  0xFF747474, 0xFF848484, 0xFF868686, 0xFF7D7D7D,
  0xFF7B7B7B, 0xFF7A7A7A, 0xFF7E7E7E, 0xFF858585,
  0xFF878787, 0xFF737373, 0xFF797979, 0xFF838383,
  0xFF898989, 0xFF707070, 0xFF717171, 0xFF727272,
  0xFF757575, 0xFF787878, 0xFF7C7C7C, 0xFF8A8A8A,
  0xFF8D8D8D
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalKeypadKey = {
  25,  // Number of entries
  1,   // Has transparency
  (const LCD_COLOR *)&_ColorsKeypadKey[0]
};

static GUI_CONST_STORAGE unsigned char _acKeypadKey[] = {
  /* ABS: 002 Pixels @ 00,00 */ 0, 2, 0x0D, 0x0E, 
  /* RLE: 073 Pixels @ 02,00 */ 73, 0x04, 
  /* ABS: 005 Pixels @ 75,00 */ 0, 5, 0x14, 0x16, 0x12, 0x03, 0x17, 
  /* RLE: 073 Pixels @ 02,01 */ 73, 0x05, 
  /* ABS: 005 Pixels @ 75,01 */ 0, 5, 0x0B, 0x18, 0x01, 0x07, 0x05, 
  /* RLE: 074 Pixels @ 02,02 */ 74, 0x02, 
  /* ABS: 005 Pixels @ 76,02 */ 0, 5, 0x0C, 0x08, 0x0A, 0x0B, 0x02, 
  /* RLE: 069 Pixels @ 03,03 */ 69, 0x01, 
  /* ABS: 009 Pixels @ 72,03 */ 0, 9, 0x02, 0x01, 0x02, 0x02, 0x06, 0x09, 0x07, 0x0B, 0x02, 
  /* RLE: 069 Pixels @ 03,04 */ 69, 0x01, 
  /* ABS: 009 Pixels @ 72,04 */ 0, 9, 0x02, 0x01, 0x01, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 069 Pixels @ 03,05 */ 69, 0x01, 
  /* ABS: 009 Pixels @ 72,05 */ 0, 9, 0x02, 0x01, 0x01, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 070 Pixels @ 03,06 */ 70, 0x01, 
  /* RLE: 003 Pixels @ 73,06 */ 3, 0x02, 
  /* ABS: 005 Pixels @ 76,06 */ 0, 5, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,07 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,07 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,08 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,08 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,09 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,09 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,10 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,10 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,11 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,11 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,12 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,12 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,13 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,13 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,14 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,14 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,15 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,15 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,16 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,16 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,17 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,17 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,18 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,18 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,19 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,19 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,20 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,20 */ 0, 7, 0x02, 0x02, 0x06, 0x09, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,21 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,21 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,22 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,22 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,23 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,23 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,24 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,24 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,25 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,25 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,26 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,26 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,27 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,27 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,28 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,28 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,29 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,29 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,30 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,30 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,31 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,31 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,32 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,32 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,33 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,33 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,34 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,34 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,35 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,35 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,36 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,36 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,37 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,37 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,38 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,38 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,39 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,39 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,40 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,40 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,41 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,41 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,42 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,42 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,43 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,43 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,44 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,44 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,45 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,45 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,46 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,46 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,47 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,47 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,48 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,48 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,49 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,49 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,50 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,50 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,51 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,51 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,52 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,52 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,53 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,53 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,54 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,54 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,55 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,55 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,56 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,56 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,57 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,57 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x07, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,58 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,58 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,59 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,59 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,60 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,60 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,61 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,61 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,62 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,62 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,63 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,63 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,64 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,64 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,65 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,65 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,66 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,66 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 071 Pixels @ 03,67 */ 71, 0x01, 
  /* ABS: 007 Pixels @ 74,67 */ 0, 7, 0x02, 0x02, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 070 Pixels @ 03,68 */ 70, 0x01, 
  /* RLE: 003 Pixels @ 73,68 */ 3, 0x02, 
  /* ABS: 005 Pixels @ 76,68 */ 0, 5, 0x06, 0x08, 0x0A, 0x05, 0x02, 
  /* RLE: 070 Pixels @ 03,69 */ 70, 0x01, 
  /* RLE: 003 Pixels @ 73,69 */ 3, 0x02, 
  /* ABS: 004 Pixels @ 76,69 */ 0, 4, 0x06, 0x08, 0x07, 0x05, 
  /* RLE: 071 Pixels @ 02,70 */ 71, 0x02, 
  /* RLE: 003 Pixels @ 73,70 */ 3, 0x01, 
  /* ABS: 004 Pixels @ 76,70 */ 0, 4, 0x06, 0x08, 0x01, 0x0C, 
  /* RLE: 072 Pixels @ 02,71 */ 72, 0x03, 
  /* ABS: 006 Pixels @ 74,71 */ 0, 6, 0x0F, 0x0F, 0x10, 0x0A, 0x01, 0x0C, 
  /* RLE: 074 Pixels @ 02,72 */ 74, 0x03, 
  /* ABS: 004 Pixels @ 76,72 */ 0, 4, 0x10, 0x07, 0x13, 0x15, 
  /* RLE: 073 Pixels @ 02,73 */ 73, 0x04, 
  /* ABS: 003 Pixels @ 75,73 */ 0, 3, 0x0D, 0x0E, 0x11, 
  0
};  // 809 bytes for 5772 pixels

GUI_CONST_STORAGE GUI_BITMAP bmKeypadKey = {
  78, // xSize
  74, // ySize
  78, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (const unsigned char *)_acKeypadKey,  // Pointer to picture data (indices)
  &_PalKeypadKey,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
