/*********************************************************************
*            (c) 1998 - 2023 SEGGER Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (NXP) for emWin V6.32.                     *
*        Compiled Feb 16 2023, 09:23:17                              *
*                                                                    *
*        (c) 1998 - 2023 SEGGER Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: menu                                                  *
* Dimensions:  60 * 46                                               *
* NumColors:   16                                                    *
* NumBytes:    1005                                                  *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmmenu;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsmenu[] = {
#if (GUI_USE_ARGB == 0)
  0xFFFFFF, 0x7F7F7F, 0x696969, 0x686868,
  0x6B6B6B, 0x737373, 0x6B6A6B, 0x706F71,
  0x585758, 0x585859, 0x5C5C5C, 0x616161,
  0x6D6D6E, 0x6F6E70, 0x717171, 0x000000
#else
  0xFFFFFFFF, 0xFF7F7F7F, 0xFF696969, 0xFF686868,
  0xFF6B6B6B, 0xFF737373, 0xFF6B6A6B, 0xFF716F70,
  0xFF585758, 0xFF595858, 0xFF5C5C5C, 0xFF616161,
  0xFF6E6D6D, 0xFF706E6F, 0xFF717171, 0xFF000000
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palmenu = {
  16,  // Number of entries
  1,   // Has transparency
  (const LCD_COLOR *)&_Colorsmenu[0]
};

static GUI_CONST_STORAGE unsigned char _acmenu[] = {
  /* RLE: 183 Pixels @ 00,00 */ 183, 0x01, 
  /* RLE: 054 Pixels @ 03,03 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,03 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,04 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,04 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,05 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,05 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,06 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,06 */ 6, 0x01, 
  /* RLE: 013 Pixels @ 03,07 */ 13, 0x00, 
  /* RLE: 005 Pixels @ 16,07 */ 5, 0x02, 
  /* RLE: 007 Pixels @ 21,07 */ 7, 0x00, 
  /* RLE: 005 Pixels @ 28,07 */ 5, 0x02, 
  /* RLE: 007 Pixels @ 33,07 */ 7, 0x00, 
  /* RLE: 005 Pixels @ 40,07 */ 5, 0x02, 
  /* RLE: 012 Pixels @ 45,07 */ 12, 0x00, 
  /* RLE: 006 Pixels @ 57,07 */ 6, 0x01, 
  /* RLE: 012 Pixels @ 03,08 */ 12, 0x00, 
  /* RLE: 007 Pixels @ 15,08 */ 7, 0x02, 
  /* RLE: 005 Pixels @ 22,08 */ 5, 0x00, 
  /* RLE: 007 Pixels @ 27,08 */ 7, 0x02, 
  /* RLE: 005 Pixels @ 34,08 */ 5, 0x00, 
  /* RLE: 007 Pixels @ 39,08 */ 7, 0x02, 
  /* RLE: 011 Pixels @ 46,08 */ 11, 0x00, 
  /* RLE: 006 Pixels @ 57,08 */ 6, 0x01, 
  /* RLE: 011 Pixels @ 03,09 */ 11, 0x00, 
  /* RLE: 003 Pixels @ 14,09 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 17,09 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 20,09 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 23,09 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 26,09 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 29,09 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 32,09 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 35,09 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 38,09 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 41,09 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 44,09 */ 3, 0x02, 
  /* RLE: 010 Pixels @ 47,09 */ 10, 0x00, 
  /* RLE: 006 Pixels @ 57,09 */ 6, 0x01, 
  /* RLE: 011 Pixels @ 03,10 */ 11, 0x00, 
  /* ABS: 002 Pixels @ 14,10 */ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 16,10 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 21,10 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 28,10 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 33,10 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 40,10 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 45,10 */ 0, 2, 0x02, 0x02, 
  /* RLE: 010 Pixels @ 47,10 */ 10, 0x00, 
  /* RLE: 006 Pixels @ 57,10 */ 6, 0x01, 
  /* RLE: 010 Pixels @ 03,11 */ 10, 0x00, 
  /* RLE: 003 Pixels @ 13,11 */ 3, 0x02, 
  /* RLE: 005 Pixels @ 16,11 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 21,11 */ 0, 7, 0x03, 0x02, 0x05, 0x00, 0x04, 0x02, 0x05, 
  /* RLE: 005 Pixels @ 28,11 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 33,11 */ 0, 7, 0x05, 0x02, 0x03, 0x00, 0x02, 0x02, 0x03, 
  /* RLE: 005 Pixels @ 40,11 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 45,11 */ 3, 0x02, 
  /* RLE: 009 Pixels @ 48,11 */ 9, 0x00, 
  /* RLE: 006 Pixels @ 57,11 */ 6, 0x01, 
  /* RLE: 010 Pixels @ 03,12 */ 10, 0x00, 
  /* ABS: 003 Pixels @ 13,12 */ 0, 3, 0x03, 0x02, 0x03, 
  /* RLE: 005 Pixels @ 16,12 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 21,12 */ 3, 0x02, 
  /* ABS: 004 Pixels @ 24,12 */ 0, 4, 0x00, 0x04, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 28,12 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 33,12 */ 0, 7, 0x02, 0x02, 0x04, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 40,12 */ 5, 0x00, 
  /* ABS: 003 Pixels @ 45,12 */ 0, 3, 0x04, 0x02, 0x02, 
  /* RLE: 009 Pixels @ 48,12 */ 9, 0x00, 
  /* RLE: 006 Pixels @ 57,12 */ 6, 0x01, 
  /* RLE: 011 Pixels @ 03,13 */ 11, 0x00, 
  /* ABS: 002 Pixels @ 14,13 */ 0, 2, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 16,13 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 21,13 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 28,13 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 33,13 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 005 Pixels @ 40,13 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 45,13 */ 0, 2, 0x02, 0x02, 
  /* RLE: 010 Pixels @ 47,13 */ 10, 0x00, 
  /* RLE: 006 Pixels @ 57,13 */ 6, 0x01, 
  /* RLE: 011 Pixels @ 03,14 */ 11, 0x00, 
  /* RLE: 003 Pixels @ 14,14 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 17,14 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 20,14 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 23,14 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 26,14 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 29,14 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 32,14 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 35,14 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 38,14 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 41,14 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 44,14 */ 3, 0x02, 
  /* RLE: 010 Pixels @ 47,14 */ 10, 0x00, 
  /* RLE: 006 Pixels @ 57,14 */ 6, 0x01, 
  /* RLE: 012 Pixels @ 03,15 */ 12, 0x00, 
  /* RLE: 007 Pixels @ 15,15 */ 7, 0x02, 
  /* RLE: 005 Pixels @ 22,15 */ 5, 0x00, 
  /* RLE: 007 Pixels @ 27,15 */ 7, 0x02, 
  /* RLE: 005 Pixels @ 34,15 */ 5, 0x00, 
  /* RLE: 007 Pixels @ 39,15 */ 7, 0x02, 
  /* RLE: 011 Pixels @ 46,15 */ 11, 0x00, 
  /* RLE: 006 Pixels @ 57,15 */ 6, 0x01, 
  /* RLE: 013 Pixels @ 03,16 */ 13, 0x00, 
  /* RLE: 005 Pixels @ 16,16 */ 5, 0x02, 
  /* RLE: 007 Pixels @ 21,16 */ 7, 0x00, 
  /* RLE: 005 Pixels @ 28,16 */ 5, 0x02, 
  /* RLE: 007 Pixels @ 33,16 */ 7, 0x00, 
  /* RLE: 004 Pixels @ 40,16 */ 4, 0x02, 
  /* RLE: 013 Pixels @ 44,16 */ 13, 0x00, 
  /* RLE: 006 Pixels @ 57,16 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,17 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,17 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,18 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,18 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,19 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,19 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,20 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,20 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,21 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,21 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,22 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,22 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,23 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 07,23 */ 6, 0x02, 
  /* ABS: 006 Pixels @ 13,23 */ 0, 6, 0x00, 0x00, 0x03, 0x02, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 19,23 */ 7, 0x00, 
  /* RLE: 004 Pixels @ 26,23 */ 4, 0x02, 
  /* RLE: 004 Pixels @ 30,23 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 34,23 */ 0, 2, 0x02, 0x03, 
  /* RLE: 004 Pixels @ 36,23 */ 4, 0x02, 
  /* RLE: 005 Pixels @ 40,23 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 45,23 */ 1, 0x02, 
  /* RLE: 005 Pixels @ 46,23 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 51,23 */ 0, 2, 0x03, 0x03, 
  /* RLE: 004 Pixels @ 53,23 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,23 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,24 */ 4, 0x00, 
  /* RLE: 014 Pixels @ 07,24 */ 14, 0x02, 
  /* RLE: 003 Pixels @ 21,24 */ 3, 0x00, 
  /* RLE: 007 Pixels @ 24,24 */ 7, 0x02, 
  /* RLE: 003 Pixels @ 31,24 */ 3, 0x00, 
  /* RLE: 007 Pixels @ 34,24 */ 7, 0x02, 
  /* RLE: 003 Pixels @ 41,24 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 44,24 */ 3, 0x02, 
  /* RLE: 004 Pixels @ 47,24 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,24 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,24 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,24 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,25 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 07,25 */ 0, 5, 0x02, 0x02, 0x03, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 12,25 */ 4, 0x02, 
  /* ABS: 031 Pixels @ 16,25 */ 0, 31, 0x00, 0x00, 0x02, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 0x05, 0x00, 0x00, 0x02, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,25 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,25 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,25 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,25 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,26 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,26 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 09,26 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,26 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,26 */ 4, 0x00, 
  /* ABS: 017 Pixels @ 19,26 */ 0, 17, 0x02, 0x02, 0x00, 0x00, 0x03, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,26 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 40,26 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,26 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,26 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,26 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,26 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,27 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,27 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 09,27 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,27 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,27 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 19,27 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 26,27 */ 4, 0x00, 
  /* ABS: 006 Pixels @ 30,27 */ 0, 6, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,27 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 40,27 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,27 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,27 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,27 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,27 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,28 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,28 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 09,28 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,28 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,28 */ 4, 0x00, 
  /* ABS: 017 Pixels @ 19,28 */ 0, 17, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,28 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 40,28 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,28 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,28 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,28 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,28 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,29 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,29 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 09,29 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,29 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,29 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 19,29 */ 0, 5, 0x02, 0x02, 0x00, 0x00, 0x03, 
  /* RLE: 008 Pixels @ 24,29 */ 8, 0x02, 
  /* ABS: 004 Pixels @ 32,29 */ 0, 4, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,29 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 40,29 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,29 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,29 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,29 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,29 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,30 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,30 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 09,30 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,30 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,30 */ 4, 0x00, 
  /* ABS: 004 Pixels @ 19,30 */ 0, 4, 0x02, 0x02, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 23,30 */ 7, 0x02, 
  /* ABS: 006 Pixels @ 30,30 */ 0, 6, 0x06, 0x00, 0x00, 0x00, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,30 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 40,30 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,30 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,30 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,30 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,30 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,31 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,31 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 09,31 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,31 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,31 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 19,31 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x03, 
  /* RLE: 008 Pixels @ 26,31 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 34,31 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,31 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 40,31 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,31 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,31 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,31 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,31 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,32 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,32 */ 0, 2, 0x0C, 0x02, 
  /* RLE: 004 Pixels @ 09,32 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,32 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,32 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 19,32 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 008 Pixels @ 26,32 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 34,32 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,32 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 40,32 */ 0, 7, 0x02, 0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 47,32 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 51,32 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 53,32 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,32 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,33 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,33 */ 0, 2, 0x0E, 0x06, 
  /* RLE: 004 Pixels @ 09,33 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,33 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 15,33 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 19,33 */ 0, 5, 0x02, 0x02, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 24,33 */ 7, 0x02, 
  /* RLE: 003 Pixels @ 31,33 */ 3, 0x00, 
  /* ABS: 002 Pixels @ 34,33 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,33 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 40,33 */ 0, 5, 0x02, 0x02, 0x00, 0x00, 0x00, 
  /* RLE: 008 Pixels @ 45,33 */ 8, 0x02, 
  /* RLE: 004 Pixels @ 53,33 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,33 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 03,34 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 07,34 */ 0, 2, 0x0B, 0x0A, 
  /* RLE: 004 Pixels @ 09,34 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 13,34 */ 0, 2, 0x09, 0x07, 
  /* RLE: 004 Pixels @ 15,34 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 19,34 */ 0, 2, 0x08, 0x07, 
  /* RLE: 004 Pixels @ 21,34 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 25,34 */ 1, 0x0D, 
  /* RLE: 005 Pixels @ 26,34 */ 5, 0x02, 
  /* RLE: 003 Pixels @ 31,34 */ 3, 0x00, 
  /* ABS: 002 Pixels @ 34,34 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 36,34 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 40,34 */ 0, 2, 0x02, 0x02, 
  /* RLE: 004 Pixels @ 42,34 */ 4, 0x00, 
  /* RLE: 007 Pixels @ 46,34 */ 7, 0x02, 
  /* RLE: 004 Pixels @ 53,34 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 57,34 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,35 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,35 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,36 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,36 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,37 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,37 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,38 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,38 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,39 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,39 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,40 */ 54, 0x00, 
  /* RLE: 006 Pixels @ 57,40 */ 6, 0x01, 
  /* RLE: 054 Pixels @ 03,41 */ 54, 0x00, 
  /* RLE: 243 Pixels @ 57,41 */ 243, 0x01, 
  0
};  // 909 bytes for 2760 pixels

GUI_CONST_STORAGE GUI_BITMAP bmmenu = {
  60, // xSize
  46, // ySize
  60, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (const unsigned char *)_acmenu,  // Pointer to picture data (indices)
  &_Palmenu,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
