/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: forwardbutton_M                                       *
* Dimensions:  58 * 58                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsforwardbutton_M[] = {
     0xFFFFFF,0xFF0000,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palforwardbutton_M = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsforwardbutton_M[0]
};

static GUI_CONST_STORAGE unsigned char acforwardbutton_M[] = {
  /* RLE: 413 Pixels @ 000,000*/ 254, 0x00, 159, 0x00, 
  /* RLE: 009 Pixels @ 007,007*/ 9, 0x01, 
  /* RLE: 009 Pixels @ 016,007*/ 9, 0x00, 
  /* RLE: 006 Pixels @ 025,007*/ 6, 0x01, 
  /* RLE: 034 Pixels @ 031,007*/ 34, 0x00, 
  /* RLE: 009 Pixels @ 007,008*/ 9, 0x01, 
  /* RLE: 009 Pixels @ 016,008*/ 9, 0x00, 
  /* RLE: 006 Pixels @ 025,008*/ 6, 0x01, 
  /* RLE: 034 Pixels @ 031,008*/ 34, 0x00, 
  /* RLE: 009 Pixels @ 007,009*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,009*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,009*/ 7, 0x00, 
  /* RLE: 008 Pixels @ 025,009*/ 8, 0x01, 
  /* RLE: 032 Pixels @ 033,009*/ 32, 0x00, 
  /* RLE: 009 Pixels @ 007,010*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,010*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,010*/ 7, 0x00, 
  /* RLE: 008 Pixels @ 025,010*/ 8, 0x01, 
  /* RLE: 032 Pixels @ 033,010*/ 32, 0x00, 
  /* RLE: 009 Pixels @ 007,011*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,011*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,011*/ 7, 0x00, 
  /* RLE: 009 Pixels @ 025,011*/ 9, 0x01, 
  /* RLE: 031 Pixels @ 034,011*/ 31, 0x00, 
  /* RLE: 009 Pixels @ 007,012*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,012*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,012*/ 7, 0x00, 
  /* RLE: 009 Pixels @ 025,012*/ 9, 0x01, 
  /* RLE: 031 Pixels @ 034,012*/ 31, 0x00, 
  /* RLE: 009 Pixels @ 007,013*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,013*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,013*/ 7, 0x00, 
  /* RLE: 011 Pixels @ 025,013*/ 11, 0x01, 
  /* RLE: 029 Pixels @ 036,013*/ 29, 0x00, 
  /* RLE: 009 Pixels @ 007,014*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,014*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,014*/ 7, 0x00, 
  /* RLE: 011 Pixels @ 025,014*/ 11, 0x01, 
  /* RLE: 029 Pixels @ 036,014*/ 29, 0x00, 
  /* RLE: 009 Pixels @ 007,015*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,015*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,015*/ 7, 0x00, 
  /* RLE: 013 Pixels @ 025,015*/ 13, 0x01, 
  /* RLE: 027 Pixels @ 038,015*/ 27, 0x00, 
  /* RLE: 009 Pixels @ 007,016*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,016*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,016*/ 7, 0x00, 
  /* RLE: 015 Pixels @ 025,016*/ 15, 0x01, 
  /* RLE: 025 Pixels @ 040,016*/ 25, 0x00, 
  /* RLE: 009 Pixels @ 007,017*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,017*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,017*/ 7, 0x00, 
  /* RLE: 015 Pixels @ 025,017*/ 15, 0x01, 
  /* RLE: 025 Pixels @ 040,017*/ 25, 0x00, 
  /* RLE: 009 Pixels @ 007,018*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,018*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,018*/ 7, 0x00, 
  /* RLE: 017 Pixels @ 025,018*/ 17, 0x01, 
  /* RLE: 023 Pixels @ 042,018*/ 23, 0x00, 
  /* RLE: 009 Pixels @ 007,019*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,019*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,019*/ 7, 0x00, 
  /* RLE: 017 Pixels @ 025,019*/ 17, 0x01, 
  /* RLE: 023 Pixels @ 042,019*/ 23, 0x00, 
  /* RLE: 009 Pixels @ 007,020*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,020*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,020*/ 7, 0x00, 
  /* RLE: 019 Pixels @ 025,020*/ 19, 0x01, 
  /* RLE: 021 Pixels @ 044,020*/ 21, 0x00, 
  /* RLE: 009 Pixels @ 007,021*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,021*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,021*/ 7, 0x00, 
  /* RLE: 019 Pixels @ 025,021*/ 19, 0x01, 
  /* RLE: 021 Pixels @ 044,021*/ 21, 0x00, 
  /* RLE: 009 Pixels @ 007,022*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,022*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,022*/ 7, 0x00, 
  /* RLE: 020 Pixels @ 025,022*/ 20, 0x01, 
  /* RLE: 020 Pixels @ 045,022*/ 20, 0x00, 
  /* RLE: 009 Pixels @ 007,023*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,023*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,023*/ 7, 0x00, 
  /* RLE: 020 Pixels @ 025,023*/ 20, 0x01, 
  /* RLE: 020 Pixels @ 045,023*/ 20, 0x00, 
  /* RLE: 009 Pixels @ 007,024*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,024*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,024*/ 7, 0x00, 
  /* RLE: 022 Pixels @ 025,024*/ 22, 0x01, 
  /* RLE: 018 Pixels @ 047,024*/ 18, 0x00, 
  /* RLE: 009 Pixels @ 007,025*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,025*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,025*/ 7, 0x00, 
  /* RLE: 024 Pixels @ 025,025*/ 24, 0x01, 
  /* RLE: 016 Pixels @ 049,025*/ 16, 0x00, 
  /* RLE: 009 Pixels @ 007,026*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,026*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,026*/ 7, 0x00, 
  /* RLE: 024 Pixels @ 025,026*/ 24, 0x01, 
  /* RLE: 016 Pixels @ 049,026*/ 16, 0x00, 
  /* RLE: 009 Pixels @ 007,027*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,027*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,027*/ 7, 0x00, 
  /* RLE: 026 Pixels @ 025,027*/ 26, 0x01, 
  /* RLE: 014 Pixels @ 051,027*/ 14, 0x00, 
  /* RLE: 009 Pixels @ 007,028*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,028*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,028*/ 7, 0x00, 
  /* RLE: 026 Pixels @ 025,028*/ 26, 0x01, 
  /* RLE: 014 Pixels @ 051,028*/ 14, 0x00, 
  /* RLE: 009 Pixels @ 007,029*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,029*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,029*/ 7, 0x00, 
  /* RLE: 026 Pixels @ 025,029*/ 26, 0x01, 
  /* ABS: 002 Pixels @ 051,029*/ 0, 2, 0x02, 0x02, 
  /* RLE: 012 Pixels @ 053,029*/ 12, 0x00, 
  /* RLE: 009 Pixels @ 007,030*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,030*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,030*/ 7, 0x00, 
  /* RLE: 026 Pixels @ 025,030*/ 26, 0x01, 
  /* ABS: 002 Pixels @ 051,030*/ 0, 2, 0x02, 0x02, 
  /* RLE: 012 Pixels @ 053,030*/ 12, 0x00, 
  /* RLE: 009 Pixels @ 007,031*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,031*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,031*/ 7, 0x00, 
  /* RLE: 024 Pixels @ 025,031*/ 24, 0x01, 
  /* RLE: 004 Pixels @ 049,031*/ 4, 0x02, 
  /* RLE: 012 Pixels @ 053,031*/ 12, 0x00, 
  /* RLE: 009 Pixels @ 007,032*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,032*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,032*/ 7, 0x00, 
  /* RLE: 024 Pixels @ 025,032*/ 24, 0x01, 
  /* RLE: 004 Pixels @ 049,032*/ 4, 0x02, 
  /* RLE: 012 Pixels @ 053,032*/ 12, 0x00, 
  /* RLE: 009 Pixels @ 007,033*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,033*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,033*/ 7, 0x00, 
  /* RLE: 022 Pixels @ 025,033*/ 22, 0x01, 
  /* RLE: 004 Pixels @ 047,033*/ 4, 0x02, 
  /* RLE: 014 Pixels @ 051,033*/ 14, 0x00, 
  /* RLE: 009 Pixels @ 007,034*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,034*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,034*/ 7, 0x00, 
  /* RLE: 020 Pixels @ 025,034*/ 20, 0x01, 
  /* RLE: 004 Pixels @ 045,034*/ 4, 0x02, 
  /* RLE: 016 Pixels @ 049,034*/ 16, 0x00, 
  /* RLE: 009 Pixels @ 007,035*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,035*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,035*/ 7, 0x00, 
  /* RLE: 020 Pixels @ 025,035*/ 20, 0x01, 
  /* RLE: 004 Pixels @ 045,035*/ 4, 0x02, 
  /* RLE: 016 Pixels @ 049,035*/ 16, 0x00, 
  /* RLE: 009 Pixels @ 007,036*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,036*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,036*/ 7, 0x00, 
  /* RLE: 019 Pixels @ 025,036*/ 19, 0x01, 
  /* RLE: 003 Pixels @ 044,036*/ 3, 0x02, 
  /* RLE: 018 Pixels @ 047,036*/ 18, 0x00, 
  /* RLE: 009 Pixels @ 007,037*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,037*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,037*/ 7, 0x00, 
  /* RLE: 019 Pixels @ 025,037*/ 19, 0x01, 
  /* RLE: 003 Pixels @ 044,037*/ 3, 0x02, 
  /* RLE: 018 Pixels @ 047,037*/ 18, 0x00, 
  /* RLE: 009 Pixels @ 007,038*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,038*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,038*/ 7, 0x00, 
  /* RLE: 017 Pixels @ 025,038*/ 17, 0x01, 
  /* RLE: 003 Pixels @ 042,038*/ 3, 0x02, 
  /* RLE: 020 Pixels @ 045,038*/ 20, 0x00, 
  /* RLE: 009 Pixels @ 007,039*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,039*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,039*/ 7, 0x00, 
  /* RLE: 017 Pixels @ 025,039*/ 17, 0x01, 
  /* RLE: 003 Pixels @ 042,039*/ 3, 0x02, 
  /* RLE: 020 Pixels @ 045,039*/ 20, 0x00, 
  /* RLE: 009 Pixels @ 007,040*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,040*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,040*/ 7, 0x00, 
  /* RLE: 015 Pixels @ 025,040*/ 15, 0x01, 
  /* RLE: 004 Pixels @ 040,040*/ 4, 0x02, 
  /* RLE: 021 Pixels @ 044,040*/ 21, 0x00, 
  /* RLE: 009 Pixels @ 007,041*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,041*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,041*/ 7, 0x00, 
  /* RLE: 015 Pixels @ 025,041*/ 15, 0x01, 
  /* RLE: 004 Pixels @ 040,041*/ 4, 0x02, 
  /* RLE: 021 Pixels @ 044,041*/ 21, 0x00, 
  /* RLE: 009 Pixels @ 007,042*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,042*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,042*/ 7, 0x00, 
  /* RLE: 013 Pixels @ 025,042*/ 13, 0x01, 
  /* RLE: 004 Pixels @ 038,042*/ 4, 0x02, 
  /* RLE: 023 Pixels @ 042,042*/ 23, 0x00, 
  /* RLE: 009 Pixels @ 007,043*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,043*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,043*/ 7, 0x00, 
  /* RLE: 013 Pixels @ 025,043*/ 13, 0x01, 
  /* RLE: 004 Pixels @ 038,043*/ 4, 0x02, 
  /* RLE: 023 Pixels @ 042,043*/ 23, 0x00, 
  /* RLE: 009 Pixels @ 007,044*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,044*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,044*/ 7, 0x00, 
  /* RLE: 011 Pixels @ 025,044*/ 11, 0x01, 
  /* RLE: 004 Pixels @ 036,044*/ 4, 0x02, 
  /* RLE: 025 Pixels @ 040,044*/ 25, 0x00, 
  /* RLE: 009 Pixels @ 007,045*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,045*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,045*/ 7, 0x00, 
  /* RLE: 009 Pixels @ 025,045*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 034,045*/ 4, 0x02, 
  /* RLE: 027 Pixels @ 038,045*/ 27, 0x00, 
  /* RLE: 009 Pixels @ 007,046*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,046*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,046*/ 7, 0x00, 
  /* RLE: 009 Pixels @ 025,046*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 034,046*/ 4, 0x02, 
  /* RLE: 027 Pixels @ 038,046*/ 27, 0x00, 
  /* RLE: 009 Pixels @ 007,047*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,047*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,047*/ 7, 0x00, 
  /* RLE: 008 Pixels @ 025,047*/ 8, 0x01, 
  /* RLE: 003 Pixels @ 033,047*/ 3, 0x02, 
  /* RLE: 029 Pixels @ 036,047*/ 29, 0x00, 
  /* RLE: 009 Pixels @ 007,048*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,048*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,048*/ 7, 0x00, 
  /* RLE: 008 Pixels @ 025,048*/ 8, 0x01, 
  /* RLE: 003 Pixels @ 033,048*/ 3, 0x02, 
  /* RLE: 029 Pixels @ 036,048*/ 29, 0x00, 
  /* RLE: 009 Pixels @ 007,049*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,049*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,049*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 025,049*/ 6, 0x01, 
  /* RLE: 003 Pixels @ 031,049*/ 3, 0x02, 
  /* RLE: 031 Pixels @ 034,049*/ 31, 0x00, 
  /* RLE: 009 Pixels @ 007,050*/ 9, 0x01, 
  /* ABS: 002 Pixels @ 016,050*/ 0, 2, 0x02, 0x02, 
  /* RLE: 007 Pixels @ 018,050*/ 7, 0x00, 
  /* RLE: 006 Pixels @ 025,050*/ 6, 0x01, 
  /* RLE: 003 Pixels @ 031,050*/ 3, 0x02, 
  /* RLE: 033 Pixels @ 034,050*/ 33, 0x00, 
  /* RLE: 009 Pixels @ 009,051*/ 9, 0x02, 
  /* RLE: 009 Pixels @ 018,051*/ 9, 0x00, 
  /* RLE: 006 Pixels @ 027,051*/ 6, 0x02, 
  /* RLE: 034 Pixels @ 033,051*/ 34, 0x00, 
  /* RLE: 009 Pixels @ 009,052*/ 9, 0x02, 
  /* RLE: 009 Pixels @ 018,052*/ 9, 0x00, 
  /* RLE: 006 Pixels @ 027,052*/ 6, 0x02, 
  /* RLE: 315 Pixels @ 033,052*/ 254, 0x00, 61, 0x00, 


  0};  /* 590 bytes for 3364 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmforwardbutton_M = {
  58, /* XSize */
  58, /* YSize */
  58, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acforwardbutton_M,  /* Pointer to picture data (indices) */
  &Palforwardbutton_M,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
