/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: playbutton_M                                          *
* Dimensions:  58 * 58                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsplaybutton_M[] = {
     0xFFFFFF,0x00FF00,0x808080
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palplaybutton_M = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsplaybutton_M[0]
};

static GUI_CONST_STORAGE unsigned char acplaybutton_M[] = {
  /* RLE: 424 Pixels @ 000,000*/ 254, 0x00, 170, 0x00, 
  /* RLE: 006 Pixels @ 018,007*/ 6, 0x01, 
  /* RLE: 052 Pixels @ 024,007*/ 52, 0x00, 
  /* RLE: 006 Pixels @ 018,008*/ 6, 0x01, 
  /* RLE: 052 Pixels @ 024,008*/ 52, 0x00, 
  /* RLE: 007 Pixels @ 018,009*/ 7, 0x01, 
  /* RLE: 051 Pixels @ 025,009*/ 51, 0x00, 
  /* RLE: 007 Pixels @ 018,010*/ 7, 0x01, 
  /* RLE: 051 Pixels @ 025,010*/ 51, 0x00, 
  /* RLE: 009 Pixels @ 018,011*/ 9, 0x01, 
  /* RLE: 049 Pixels @ 027,011*/ 49, 0x00, 
  /* RLE: 009 Pixels @ 018,012*/ 9, 0x01, 
  /* RLE: 049 Pixels @ 027,012*/ 49, 0x00, 
  /* RLE: 011 Pixels @ 018,013*/ 11, 0x01, 
  /* RLE: 047 Pixels @ 029,013*/ 47, 0x00, 
  /* RLE: 011 Pixels @ 018,014*/ 11, 0x01, 
  /* RLE: 047 Pixels @ 029,014*/ 47, 0x00, 
  /* RLE: 013 Pixels @ 018,015*/ 13, 0x01, 
  /* RLE: 045 Pixels @ 031,015*/ 45, 0x00, 
  /* RLE: 015 Pixels @ 018,016*/ 15, 0x01, 
  /* RLE: 043 Pixels @ 033,016*/ 43, 0x00, 
  /* RLE: 015 Pixels @ 018,017*/ 15, 0x01, 
  /* RLE: 043 Pixels @ 033,017*/ 43, 0x00, 
  /* RLE: 016 Pixels @ 018,018*/ 16, 0x01, 
  /* RLE: 042 Pixels @ 034,018*/ 42, 0x00, 
  /* RLE: 016 Pixels @ 018,019*/ 16, 0x01, 
  /* RLE: 042 Pixels @ 034,019*/ 42, 0x00, 
  /* RLE: 018 Pixels @ 018,020*/ 18, 0x01, 
  /* RLE: 040 Pixels @ 036,020*/ 40, 0x00, 
  /* RLE: 018 Pixels @ 018,021*/ 18, 0x01, 
  /* RLE: 040 Pixels @ 036,021*/ 40, 0x00, 
  /* RLE: 020 Pixels @ 018,022*/ 20, 0x01, 
  /* RLE: 038 Pixels @ 038,022*/ 38, 0x00, 
  /* RLE: 020 Pixels @ 018,023*/ 20, 0x01, 
  /* RLE: 038 Pixels @ 038,023*/ 38, 0x00, 
  /* RLE: 022 Pixels @ 018,024*/ 22, 0x01, 
  /* RLE: 036 Pixels @ 040,024*/ 36, 0x00, 
  /* RLE: 024 Pixels @ 018,025*/ 24, 0x01, 
  /* RLE: 034 Pixels @ 042,025*/ 34, 0x00, 
  /* RLE: 024 Pixels @ 018,026*/ 24, 0x01, 
  /* RLE: 034 Pixels @ 042,026*/ 34, 0x00, 
  /* RLE: 026 Pixels @ 018,027*/ 26, 0x01, 
  /* RLE: 032 Pixels @ 044,027*/ 32, 0x00, 
  /* RLE: 026 Pixels @ 018,028*/ 26, 0x01, 
  /* RLE: 032 Pixels @ 044,028*/ 32, 0x00, 
  /* RLE: 026 Pixels @ 018,029*/ 26, 0x01, 
  /* RLE: 001 Pixels @ 044,029*/ 1, 0x02, 
  /* RLE: 031 Pixels @ 045,029*/ 31, 0x00, 
  /* RLE: 026 Pixels @ 018,030*/ 26, 0x01, 
  /* RLE: 001 Pixels @ 044,030*/ 1, 0x02, 
  /* RLE: 031 Pixels @ 045,030*/ 31, 0x00, 
  /* RLE: 024 Pixels @ 018,031*/ 24, 0x01, 
  /* RLE: 003 Pixels @ 042,031*/ 3, 0x02, 
  /* RLE: 031 Pixels @ 045,031*/ 31, 0x00, 
  /* RLE: 024 Pixels @ 018,032*/ 24, 0x01, 
  /* RLE: 003 Pixels @ 042,032*/ 3, 0x02, 
  /* RLE: 031 Pixels @ 045,032*/ 31, 0x00, 
  /* RLE: 022 Pixels @ 018,033*/ 22, 0x01, 
  /* RLE: 004 Pixels @ 040,033*/ 4, 0x02, 
  /* RLE: 032 Pixels @ 044,033*/ 32, 0x00, 
  /* RLE: 020 Pixels @ 018,034*/ 20, 0x01, 
  /* RLE: 004 Pixels @ 038,034*/ 4, 0x02, 
  /* RLE: 034 Pixels @ 042,034*/ 34, 0x00, 
  /* RLE: 020 Pixels @ 018,035*/ 20, 0x01, 
  /* RLE: 004 Pixels @ 038,035*/ 4, 0x02, 
  /* RLE: 034 Pixels @ 042,035*/ 34, 0x00, 
  /* RLE: 018 Pixels @ 018,036*/ 18, 0x01, 
  /* RLE: 004 Pixels @ 036,036*/ 4, 0x02, 
  /* RLE: 036 Pixels @ 040,036*/ 36, 0x00, 
  /* RLE: 018 Pixels @ 018,037*/ 18, 0x01, 
  /* RLE: 004 Pixels @ 036,037*/ 4, 0x02, 
  /* RLE: 036 Pixels @ 040,037*/ 36, 0x00, 
  /* RLE: 016 Pixels @ 018,038*/ 16, 0x01, 
  /* RLE: 004 Pixels @ 034,038*/ 4, 0x02, 
  /* RLE: 038 Pixels @ 038,038*/ 38, 0x00, 
  /* RLE: 016 Pixels @ 018,039*/ 16, 0x01, 
  /* RLE: 004 Pixels @ 034,039*/ 4, 0x02, 
  /* RLE: 038 Pixels @ 038,039*/ 38, 0x00, 
  /* RLE: 015 Pixels @ 018,040*/ 15, 0x01, 
  /* RLE: 003 Pixels @ 033,040*/ 3, 0x02, 
  /* RLE: 040 Pixels @ 036,040*/ 40, 0x00, 
  /* RLE: 015 Pixels @ 018,041*/ 15, 0x01, 
  /* RLE: 003 Pixels @ 033,041*/ 3, 0x02, 
  /* RLE: 040 Pixels @ 036,041*/ 40, 0x00, 
  /* RLE: 013 Pixels @ 018,042*/ 13, 0x01, 
  /* RLE: 003 Pixels @ 031,042*/ 3, 0x02, 
  /* RLE: 042 Pixels @ 034,042*/ 42, 0x00, 
  /* RLE: 013 Pixels @ 018,043*/ 13, 0x01, 
  /* RLE: 003 Pixels @ 031,043*/ 3, 0x02, 
  /* RLE: 042 Pixels @ 034,043*/ 42, 0x00, 
  /* RLE: 011 Pixels @ 018,044*/ 11, 0x01, 
  /* RLE: 004 Pixels @ 029,044*/ 4, 0x02, 
  /* RLE: 043 Pixels @ 033,044*/ 43, 0x00, 
  /* RLE: 009 Pixels @ 018,045*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 027,045*/ 4, 0x02, 
  /* RLE: 045 Pixels @ 031,045*/ 45, 0x00, 
  /* RLE: 009 Pixels @ 018,046*/ 9, 0x01, 
  /* RLE: 004 Pixels @ 027,046*/ 4, 0x02, 
  /* RLE: 045 Pixels @ 031,046*/ 45, 0x00, 
  /* RLE: 007 Pixels @ 018,047*/ 7, 0x01, 
  /* RLE: 004 Pixels @ 025,047*/ 4, 0x02, 
  /* RLE: 047 Pixels @ 029,047*/ 47, 0x00, 
  /* RLE: 007 Pixels @ 018,048*/ 7, 0x01, 
  /* RLE: 004 Pixels @ 025,048*/ 4, 0x02, 
  /* RLE: 047 Pixels @ 029,048*/ 47, 0x00, 
  /* RLE: 006 Pixels @ 018,049*/ 6, 0x01, 
  /* RLE: 003 Pixels @ 024,049*/ 3, 0x02, 
  /* RLE: 049 Pixels @ 027,049*/ 49, 0x00, 
  /* RLE: 006 Pixels @ 018,050*/ 6, 0x01, 
  /* RLE: 003 Pixels @ 024,050*/ 3, 0x02, 
  /* RLE: 051 Pixels @ 027,050*/ 51, 0x00, 
  /* RLE: 005 Pixels @ 020,051*/ 5, 0x02, 
  /* RLE: 053 Pixels @ 025,051*/ 53, 0x00, 
  /* RLE: 005 Pixels @ 020,052*/ 5, 0x02, 
  /* RLE: 323 Pixels @ 025,052*/ 254, 0x00, 69, 0x00, 


  0};  /* 234 bytes for 3364 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmplaybutton_M = {
  58, /* XSize */
  58, /* YSize */
  58, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acplaybutton_M,  /* Pointer to picture data (indices) */
  &Palplaybutton_M,  /* Pointer to palette */
  GUI_DRAW_RLE8
};

/* *** End of file *** */
