BmpCvt.exe "Buttons/Bowl.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Bowl",1,7,0 -exit
BmpCvt.exe "Buttons/EditScore.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/EditScore",1,7,0 -exit
BmpCvt.exe "Buttons/KeypadKey.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/KeypadKey",1,7,0 -exit
BmpCvt.exe "Buttons/KeypadKeyPressed.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/KeypadKeyPressed",1,7,0 -exit
BmpCvt.exe "Buttons/NameBar.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/NameBar",1,7,0 -exit
BmpCvt.exe "Buttons/NameBarSelected.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/NameBarSelected",1,7,0 -exit
BmpCvt.exe "Buttons/Options.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Options",1,7,0 -exit
BmpCvt.exe "Buttons/Practice.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Practice",1,7,0 -exit
BmpCvt.exe "Buttons/QuickStart.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/QuickStart",1,7,0 -exit
BmpCvt.exe "Buttons/RemoveBowler.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/RemoveBowler",1,7,0 -exit
BmpCvt.exe "Buttons/RemoveBowlerSelected.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/RemoveBowlerSelected",1,7,0 -exit
BmpCvt.exe "Buttons/Service.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Service",1,7,0 -exit
BmpCvt.exe "Buttons/SkipBowler.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/SkipBowler",1,7,0 -exit
BmpCvt.exe "Buttons/StandardPlay.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/StandardPlay",1,7,0 -exit
BmpCvt.exe "Buttons/Start.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Start",1,7,0 -exit
BmpCvt.exe "Buttons/Theme.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Theme",1,7,0 -exit
BmpCvt.exe "Buttons/menu.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/menu",1,7,0 -exit
BmpCvt.exe "Buttons/Cancel.png" -convertintotranspalette -transparency"000000" -saveas"Buttons/Cancel",1,7,0 -exit
BmpCvt.exe "Buttons/OK.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/OK",1,7,0 -exit
BmpCvt.exe "Buttons/Bumper.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Bumper",1,7,0 -exit
BmpCvt.exe "Buttons/BumperSelected.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/BumperSelected",1,7,0 -exit
BmpCvt.exe "Buttons/PracticeDisabled.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/PracticeDisabled",1,7,0 -exit
BmpCvt.exe "Buttons/Backspace.png" -convertintotranspalette -transparency"FFFFFF" -saveas"Buttons/Backspace",1,7,0 -exit