import os
import sys
import fileinput
import re
# This script parses thorugh the html files generated by Doxygen and adds the <h1> heading to the titles of each page
#gets the current working directory and points towards the known location of the html files
directory = os.getcwd() + "\\Docs\\html\\html"
flag = 0
for filename in os.listdir(directory):
    #print(filename)
    if filename.endswith('.html'):           
            with open(os.path.join(directory, filename,),'r') as file:
                filedata = file.read()
            # Checks for existing h1 tags
            if (bool(re.search('<h1>', filedata))) == True:
                #print('Already Applied H1 heading')
            # Used to include specific files into the main replacement     
            elif (filename.find('_simple_u_i___utility_functions') != -1):
                flag = 1
                x = re.search('<div class="title">(.*?)</div>', filedata)
                #print(x.group(1))
                filedata = filedata.replace('<div class="title">'+ x.group(1) + '</div>', '<div class="title"><h1>' + x.group(1) + '</h1></div>')
                with open(os.path.join(directory, filename), 'w') as file:
                    file.write(filedata)
            # Seperate parsing for the index html files, becase they are structured different        
            elif (filename.find('_0x') != -1 or filename.find('functions') != -1 or filename.find('globals') != -1 and flag != 1):
                y = re.search('<h3><a class="anchor" id="index_.*"></a>(.*?)</h3>', filedata)
                #print(y.group(1))
                index_letter = (re.search('- (.*?) -', y.group(1)))
                filedata = filedata.replace('<h3><a class="anchor" id="index_' + index_letter.group(1) + '"></a>'+ y.group(1) + '</h3>', '<h1><a class="anchor" id="index_' + index_letter.group(1) + '"></a>' + y.group(1) + '</h1>')
                with open(os.path.join(directory, filename), 'w') as file:
                    file.write(filedata)
            # Main replacement of h1 tags for most of the html files
            else:
                x = re.search('<div class="title">(.*?)</div>', filedata)
                #print(x.group(1))
                filedata = filedata.replace('<div class="title">'+ x.group(1) + '</div>', '<div class="title"><h1>' + x.group(1) + '</h1></div>')
                with open(os.path.join(directory, filename), 'w') as file:
                    file.write(filedata)

print("Finished adding H1 headers to html files")